# GENERATED by app/scripts/ips-obligations.mjs from hl7.fhir.uv.ips 2.0.1. Edit the generator, not this file.
#
# A Consumer's obligations are behaviours, not document content, so the test
# bed hands the Consumer the IG's own all-sections example and a tester confirms
# what the system did with it:
#   SHALL:handle     the operator attaches the import result (log or screenshot)
#                    and confirms, element by element, that it was accepted
#   SHOULD:display   the operator displays the elements, attaches a screenshot,
#                    and confirms each one from a list — one verdict per element
# Evidence files are kept by the test bed in the session report, beside the step.
# A Consumer that is a FHIR server accepting documents can be driven without a
# tester: see the last Rule.
@lang:itb-core-en@^2 @dialect:fhir-validator@^2 @actor:Consumer @spec:hl7.fhir.uv.ips@2.0.1
Feature: IPS Consumer — obligations of hl7.fhir.uv.ips 2.0.1
  An IPS Consumer actor is a system that receives an IPS document and uses the content of this document.

  Background:
    Given Consumer is the system under test
    And Tester is infrastructure
    And FHIRValidator is a fhir-validator at "http://fhir-validator:8080"
    And FHIRValidator is loaded with package "hl7.fhir.uv.ips#2.0.1"
    When Tester gets "https://hl7.org/fhir/uv/ips/Bundle-bundle-ips-all-sections.json" as $ips
    Then $ips should conform to "http://hl7.org/fhir/uv/ips/StructureDefinition/Bundle-uv-ips" ignoring slicing errors
    And Consumer is informed "Import this International Patient Summary for Patricia JORDANA into the system under test, then answer the questions that follow." with $ips

  Rule: The document: Bundle and Composition

    @profile:Bundle-uv-ips
    @covers:Bundle.identifier @covers:Bundle.timestamp @covers:Bundle.entry:composition
    Scenario: ips-consumer-001 Bundle (IPS) — the Consumer handles 3 elements and displays 1
      When Consumer submits evidence of "the import of the document completing without error (import log or screenshot)" as $handledBundleEvidence
      Then Consumer confirms each of these is accepted for "the document":
        | item              | detail |
        | identifier        |  |
        | timestamp         |  |
        | entry:composition |  |
      When Consumer is informed "Open Patricia JORDANA's summary in the system under test and display the document."
      And Consumer submits evidence of "the document displayed (screenshot)" as $displayedBundleEvidence
      Then Consumer confirms each of these is displayed for "the document":
        | item              | detail |
        | entry:composition |  |

    @profile:Composition-uv-ips
    @covers:Composition.text @covers:Composition.identifier @covers:Composition.status @covers:Composition.type
    @covers:Composition.subject @covers:Composition.subject.reference @covers:Composition.date @covers:Composition.author
    @covers:Composition.title @covers:Composition.attester @covers:Composition.attester.mode @covers:Composition.attester.time
    @covers:Composition.attester.party @covers:Composition.custodian @covers:Composition.event:careProvisioningEvent @covers:Composition.event:careProvisioningEvent.code
    @covers:Composition.event:careProvisioningEvent.period @covers:Composition.section @covers:Composition.section.title @covers:Composition.section.code
    @covers:Composition.section.text @covers:Composition.section:sectionProblems @covers:Composition.section:sectionProblems.title @covers:Composition.section:sectionProblems.text
    @covers:Composition.section:sectionProblems.entry:problem @covers:Composition.section:sectionProblems.emptyReason @covers:Composition.section:sectionAllergies @covers:Composition.section:sectionAllergies.title
    @covers:Composition.section:sectionAllergies.text @covers:Composition.section:sectionAllergies.entry:allergyOrIntolerance @covers:Composition.section:sectionAllergies.emptyReason @covers:Composition.section:sectionMedications
    @covers:Composition.section:sectionMedications.title @covers:Composition.section:sectionMedications.text @covers:Composition.section:sectionMedications.entry:medicationStatementOrRequest @covers:Composition.section:sectionMedications.emptyReason
    @covers:Composition.section:sectionImmunizations @covers:Composition.section:sectionImmunizations.title @covers:Composition.section:sectionImmunizations.text @covers:Composition.section:sectionImmunizations.entry:immunization
    @covers:Composition.section:sectionResults @covers:Composition.section:sectionResults.title @covers:Composition.section:sectionResults.text @covers:Composition.section:sectionResults.entry:results-observation-laboratory-pathology
    @covers:Composition.section:sectionResults.entry:results-observation-radiology @covers:Composition.section:sectionResults.entry:results-diagnosticReport @covers:Composition.section:sectionProceduresHx @covers:Composition.section:sectionProceduresHx.title
    @covers:Composition.section:sectionProceduresHx.text @covers:Composition.section:sectionProceduresHx.entry:procedure @covers:Composition.section:sectionMedicalDevices @covers:Composition.section:sectionMedicalDevices.title
    @covers:Composition.section:sectionMedicalDevices.text @covers:Composition.section:sectionMedicalDevices.entry:deviceStatement @covers:Composition.section:sectionAdvanceDirectives @covers:Composition.section:sectionAdvanceDirectives.title
    @covers:Composition.section:sectionAdvanceDirectives.text @covers:Composition.section:sectionAlerts @covers:Composition.section:sectionAlerts.title @covers:Composition.section:sectionAlerts.text
    @covers:Composition.section:sectionFunctionalStatus @covers:Composition.section:sectionFunctionalStatus.title @covers:Composition.section:sectionFunctionalStatus.text @covers:Composition.section:sectionPastProblems
    @covers:Composition.section:sectionPastProblems.title @covers:Composition.section:sectionPastProblems.text @covers:Composition.section:sectionPregnancyHx @covers:Composition.section:sectionPregnancyHx.title
    @covers:Composition.section:sectionPregnancyHx.text @covers:Composition.section:sectionPatientStory @covers:Composition.section:sectionPatientStory.title @covers:Composition.section:sectionPatientStory.text
    @covers:Composition.section:sectionPlanOfCare @covers:Composition.section:sectionPlanOfCare.title @covers:Composition.section:sectionPlanOfCare.text @covers:Composition.section:sectionSocialHistory
    @covers:Composition.section:sectionSocialHistory.title @covers:Composition.section:sectionSocialHistory.text @covers:Composition.section:sectionVitalSigns @covers:Composition.section:sectionVitalSigns.title
    @covers:Composition.section:sectionVitalSigns.text
    Scenario: ips-consumer-002 Composition (IPS) — the Consumer handles 81 elements and displays 77
      When Consumer submits evidence of "the import of the Composition resources completing without error (import log or screenshot)" as $handledCompositionEvidence
      Then Consumer confirms each of these is accepted for "the Composition resources":
        | item                                                                  | detail |
        | text                                                                  | (present) |
        | identifier                                                            | ac7a747c-a2c9-493c-ba39-4ac6997eed1e |
        | status                                                                | final |
        | type                                                                  | Patient summary Document |
        | subject                                                               | Patient/d174bd1a-b368-41e6-83a2-af77f… |
        | subject.reference                                                     | Patient/d174bd1a-b368-41e6-83a2-af77f… |
        | date                                                                  | 2024-09-13 |
        | author                                                                | Organization/7a17027f-acc0-4d77-bf84-… |
        | title                                                                 | International Patient Summary |
        | attester                                                              | (present) |
        | attester.mode                                                         | professional |
        | attester.time                                                         | 2024-09-13 |
        | attester.party                                                        | PractitionerRole/94d12c8d-a3df-47a7-a… |
        | custodian                                                             | Organization/7a17027f-acc0-4d77-bf84-… |
        | event:careProvisioningEvent                                           | (present) |
        | event:careProvisioningEvent.code                                      | PCPR |
        | event:careProvisioningEvent.period                                    | until 2024-09-13 |
        | section                                                               | Problem List |
        | section.title                                                         | Problem List |
        | section.code                                                          | Problem list - Reported |
        | section.text                                                          | (present) |
        | section:sectionProblems                                               | Problem List |
        | section:sectionProblems.title                                         | Problem List |
        | section:sectionProblems.text                                          | (present) |
        | section:sectionProblems.entry:problem                                 | Condition/8039e4a7-d459-454c-92a5-6c1… |
        | section:sectionProblems.emptyReason                                   |  |
        | section:sectionAllergies                                              | Allergies and Intolerances |
        | section:sectionAllergies.title                                        | Allergies and Intolerances |
        | section:sectionAllergies.text                                         | (present) |
        | section:sectionAllergies.entry:allergyOrIntolerance                   | AllergyIntolerance/9838cf73-c30d-4aa5… |
        | section:sectionAllergies.emptyReason                                  |  |
        | section:sectionMedications                                            | Medication Summary |
        | section:sectionMedications.title                                      | Medication Summary |
        | section:sectionMedications.text                                       | (present) |
        | section:sectionMedications.entry:medicationStatementOrRequest         | MedicationStatement/c3d31980-2a88-45b… |
        | section:sectionMedications.emptyReason                                |  |
        | section:sectionImmunizations                                          | Immunizations |
        | section:sectionImmunizations.title                                    | Immunizations |
        | section:sectionImmunizations.text                                     | (present) |
        | section:sectionImmunizations.entry:immunization                       | Immunization/17b5a6d7-307b-4726-8c8c-… |
        | section:sectionResults                                                | Results |
        | section:sectionResults.title                                          | Results |
        | section:sectionResults.text                                           | (present) |
        | section:sectionResults.entry:results-observation-laboratory-pathology | Observation/b0187efd-5f9b-474d-87bc-e… |
        | section:sectionResults.entry:results-observation-radiology            | Observation/b0187efd-5f9b-474d-87bc-e… |
        | section:sectionResults.entry:results-diagnosticReport                 |  |
        | section:sectionProceduresHx                                           | History of Procedures |
        | section:sectionProceduresHx.title                                     | History of Procedures |
        | section:sectionProceduresHx.text                                      | (present) |
        | section:sectionProceduresHx.entry:procedure                           | Procedure/39252 |
        | section:sectionMedicalDevices                                         | Device Use |
        | section:sectionMedicalDevices.title                                   | Device Use |
        | section:sectionMedicalDevices.text                                    | (present) |
        | section:sectionMedicalDevices.entry:deviceStatement                   | DeviceUseStatement/eumfh-70-275-1 |
        | section:sectionAdvanceDirectives                                      | Advance Directives |
        | section:sectionAdvanceDirectives.title                                | Advance Directives |
        | section:sectionAdvanceDirectives.text                                 | (present) |
        | section:sectionAlerts                                                 | Alerts |
        | section:sectionAlerts.title                                           | Alerts |
        | section:sectionAlerts.text                                            | (present) |
        | section:sectionFunctionalStatus                                       | Functional Status |
        | section:sectionFunctionalStatus.title                                 | Functional Status |
        | section:sectionFunctionalStatus.text                                  | (present) |
        | section:sectionPastProblems                                           | History of Past Problems |
        | section:sectionPastProblems.title                                     | History of Past Problems |
        | section:sectionPastProblems.text                                      | (present) |
        | section:sectionPregnancyHx                                            | History of Pregnancy |
        | section:sectionPregnancyHx.title                                      | History of Pregnancy |
        | section:sectionPregnancyHx.text                                       | (present) |
        | section:sectionPatientStory                                           | Patient Story |
        | section:sectionPatientStory.title                                     | Patient Story |
        | section:sectionPatientStory.text                                      | (present) |
        | section:sectionPlanOfCare                                             | Plan of Care |
        | section:sectionPlanOfCare.title                                       | Plan of Care |
        | section:sectionPlanOfCare.text                                        | (present) |
        | section:sectionSocialHistory                                          | Social History |
        | section:sectionSocialHistory.title                                    | Social History |
        | section:sectionSocialHistory.text                                     | (present) |
        | section:sectionVitalSigns                                             | Vital Signs |
        | section:sectionVitalSigns.title                                       | Vital Signs |
        | section:sectionVitalSigns.text                                        | (present) |
      When Consumer is informed "Open Patricia JORDANA's summary in the system under test and display the Composition resources."
      And Consumer submits evidence of "the Composition resources displayed (screenshot)" as $displayedCompositionEvidence
      Then Consumer confirms each of these is displayed for "the Composition resources":
        | item                                                                  | detail |
        | text                                                                  | (present) |
        | status                                                                | final |
        | subject                                                               | Patient/d174bd1a-b368-41e6-83a2-af77f… |
        | date                                                                  | 2024-09-13 |
        | author                                                                | Organization/7a17027f-acc0-4d77-bf84-… |
        | title                                                                 | International Patient Summary |
        | attester                                                              | (present) |
        | attester.mode                                                         | professional |
        | attester.time                                                         | 2024-09-13 |
        | attester.party                                                        | PractitionerRole/94d12c8d-a3df-47a7-a… |
        | custodian                                                             | Organization/7a17027f-acc0-4d77-bf84-… |
        | event:careProvisioningEvent                                           | (present) |
        | event:careProvisioningEvent.code                                      | PCPR |
        | event:careProvisioningEvent.period                                    | until 2024-09-13 |
        | section                                                               | Problem List |
        | section.title                                                         | Problem List |
        | section.text                                                          | (present) |
        | section:sectionProblems                                               | Problem List |
        | section:sectionProblems.title                                         | Problem List |
        | section:sectionProblems.text                                          | (present) |
        | section:sectionProblems.entry:problem                                 | Condition/8039e4a7-d459-454c-92a5-6c1… |
        | section:sectionProblems.emptyReason                                   |  |
        | section:sectionAllergies                                              | Allergies and Intolerances |
        | section:sectionAllergies.title                                        | Allergies and Intolerances |
        | section:sectionAllergies.text                                         | (present) |
        | section:sectionAllergies.entry:allergyOrIntolerance                   | AllergyIntolerance/9838cf73-c30d-4aa5… |
        | section:sectionAllergies.emptyReason                                  |  |
        | section:sectionMedications                                            | Medication Summary |
        | section:sectionMedications.title                                      | Medication Summary |
        | section:sectionMedications.text                                       | (present) |
        | section:sectionMedications.entry:medicationStatementOrRequest         | MedicationStatement/c3d31980-2a88-45b… |
        | section:sectionMedications.emptyReason                                |  |
        | section:sectionImmunizations                                          | Immunizations |
        | section:sectionImmunizations.title                                    | Immunizations |
        | section:sectionImmunizations.text                                     | (present) |
        | section:sectionImmunizations.entry:immunization                       | Immunization/17b5a6d7-307b-4726-8c8c-… |
        | section:sectionResults                                                | Results |
        | section:sectionResults.title                                          | Results |
        | section:sectionResults.text                                           | (present) |
        | section:sectionResults.entry:results-observation-laboratory-pathology | Observation/b0187efd-5f9b-474d-87bc-e… |
        | section:sectionResults.entry:results-observation-radiology            | Observation/b0187efd-5f9b-474d-87bc-e… |
        | section:sectionResults.entry:results-diagnosticReport                 |  |
        | section:sectionProceduresHx                                           | History of Procedures |
        | section:sectionProceduresHx.title                                     | History of Procedures |
        | section:sectionProceduresHx.text                                      | (present) |
        | section:sectionProceduresHx.entry:procedure                           | Procedure/39252 |
        | section:sectionMedicalDevices                                         | Device Use |
        | section:sectionMedicalDevices.title                                   | Device Use |
        | section:sectionMedicalDevices.text                                    | (present) |
        | section:sectionMedicalDevices.entry:deviceStatement                   | DeviceUseStatement/eumfh-70-275-1 |
        | section:sectionAdvanceDirectives                                      | Advance Directives |
        | section:sectionAdvanceDirectives.title                                | Advance Directives |
        | section:sectionAdvanceDirectives.text                                 | (present) |
        | section:sectionAlerts                                                 | Alerts |
        | section:sectionAlerts.title                                           | Alerts |
        | section:sectionAlerts.text                                            | (present) |
        | section:sectionFunctionalStatus                                       | Functional Status |
        | section:sectionFunctionalStatus.title                                 | Functional Status |
        | section:sectionFunctionalStatus.text                                  | (present) |
        | section:sectionPastProblems                                           | History of Past Problems |
        | section:sectionPastProblems.title                                     | History of Past Problems |
        | section:sectionPastProblems.text                                      | (present) |
        | section:sectionPregnancyHx                                            | History of Pregnancy |
        | section:sectionPregnancyHx.title                                      | History of Pregnancy |
        | section:sectionPregnancyHx.text                                       | (present) |
        | section:sectionPatientStory                                           | Patient Story |
        | section:sectionPatientStory.title                                     | Patient Story |
        | section:sectionPatientStory.text                                      | (present) |
        | section:sectionPlanOfCare                                             | Plan of Care |
        | section:sectionPlanOfCare.title                                       | Plan of Care |
        | section:sectionPlanOfCare.text                                        | (present) |
        | section:sectionSocialHistory                                          | Social History |
        | section:sectionSocialHistory.title                                    | Social History |
        | section:sectionSocialHistory.text                                     | (present) |
        | section:sectionVitalSigns                                             | Vital Signs |
        | section:sectionVitalSigns.title                                       | Vital Signs |
        | section:sectionVitalSigns.text                                        | (present) |

  Rule: The people and organisations

    @profile:Patient-uv-ips
    @covers:Patient.identifier @covers:Patient.name @covers:Patient.name.use @covers:Patient.name.text
    @covers:Patient.name.family @covers:Patient.name.given @covers:Patient.telecom @covers:Patient.gender
    @covers:Patient.birthDate @covers:Patient.address @covers:Patient.generalPractitioner
    Scenario: ips-consumer-003 Patient (IPS) — the Consumer handles 11 elements and displays 11
      When Consumer submits evidence of "the import of the Patient resources completing without error (import log or screenshot)" as $handledPatientEvidence
      Then Consumer confirms each of these is accepted for "the Patient resources":
        | item                | detail |
        | identifier          | ABC1234 |
        | name                | Patricia JORDANA |
        | name.use            | usual |
        | name.text           |  |
        | name.family         | JORDANA |
        | name.given          | Patricia |
        | telecom             | +1234567890 |
        | gender              | female |
        | birthDate           | 1956-09-30 |
        | address             | (present) |
        | generalPractitioner |  |
      When Consumer is informed "Open Patricia JORDANA's summary in the system under test and display the Patient resources."
      And Consumer submits evidence of "the Patient resources displayed (screenshot)" as $displayedPatientEvidence
      Then Consumer confirms each of these is displayed for "the Patient resources":
        | item                | detail |
        | identifier          | ABC1234 |
        | name                | Patricia JORDANA |
        | name.use            | usual |
        | name.text           |  |
        | name.family         | JORDANA |
        | name.given          | Patricia |
        | telecom             | +1234567890 |
        | gender              | female |
        | birthDate           | 1956-09-30 |
        | address             | (present) |
        | generalPractitioner |  |

    @profile:Practitioner-uv-ips
    @covers:Practitioner.name @covers:Practitioner.name.family @covers:Practitioner.name.given @covers:Practitioner.telecom
    @covers:Practitioner.address
    Scenario: ips-consumer-004 Practitioner (IPS) — the Consumer handles 5 elements and displays 5
      When Consumer submits evidence of "the import of the Practitioner resources completing without error (import log or screenshot)" as $handledPractitionerEvidence
      Then Consumer confirms each of these is accepted for "the Practitioner resources":
        | item        | detail |
        | name        | HASHIRA COORAY COORAY |
        | name.family | COORAY |
        | name.given  | HASHIRA |
        | telecom     | 07 850 9900 |
        | address     |  |
      When Consumer is informed "Open Patricia JORDANA's summary in the system under test and display the Practitioner resources."
      And Consumer submits evidence of "the Practitioner resources displayed (screenshot)" as $displayedPractitionerEvidence
      Then Consumer confirms each of these is displayed for "the Practitioner resources":
        | item        | detail |
        | name        | HASHIRA COORAY COORAY |
        | name.family | COORAY |
        | name.given  | HASHIRA |
        | telecom     | 07 850 9900 |
        | address     |  |

    @profile:PractitionerRole-uv-ips
    @covers:PractitionerRole.organization
    Scenario: ips-consumer-005 PractitionerRole (IPS) — the Consumer handles 1 element and displays 1
      When Consumer submits evidence of "the import of the PractitionerRole resources completing without error (import log or screenshot)" as $handledPractitionerRoleEvidence
      Then Consumer confirms each of these is accepted for "the PractitionerRole resources":
        | item         | detail |
        | organization |  |
      When Consumer is informed "Open Patricia JORDANA's summary in the system under test and display the PractitionerRole resources."
      And Consumer submits evidence of "the PractitionerRole resources displayed (screenshot)" as $displayedPractitionerRoleEvidence
      Then Consumer confirms each of these is displayed for "the PractitionerRole resources":
        | item         | detail |
        | organization |  |

    @profile:Organization-uv-ips
    @covers:Organization.name @covers:Organization.telecom @covers:Organization.address
    Scenario: ips-consumer-006 Organization (IPS) — the Consumer handles 3 elements and displays 3
      When Consumer submits evidence of "the import of the Organization resources completing without error (import log or screenshot)" as $handledOrganizationEvidence
      Then Consumer confirms each of these is accepted for "the Organization resources":
        | item    | detail |
        | name    | NorthCare Pukete Road-Thomas Road |
        | telecom |  |
        | address |  |
      When Consumer is informed "Open Patricia JORDANA's summary in the system under test and display the Organization resources."
      And Consumer submits evidence of "the Organization resources displayed (screenshot)" as $displayedOrganizationEvidence
      Then Consumer confirms each of these is displayed for "the Organization resources":
        | item    | detail |
        | name    | NorthCare Pukete Road-Thomas Road |
        | telecom |  |
        | address |  |

  Rule: The required sections: problems, allergies, medications

    @profile:AllergyIntolerance-uv-ips
    @covers:AllergyIntolerance.clinicalStatus @covers:AllergyIntolerance.type @covers:AllergyIntolerance.code @covers:AllergyIntolerance.patient
    @covers:AllergyIntolerance.patient.reference @covers:AllergyIntolerance.onset[x] @covers:AllergyIntolerance.onset[x]:onsetDateTime @covers:AllergyIntolerance.reaction
    @covers:AllergyIntolerance.reaction.manifestation @covers:AllergyIntolerance.reaction.severity
    Scenario: ips-consumer-007 AllergyIntolerance (IPS) — the Consumer handles 10 elements and displays 9
      When Consumer submits evidence of "the import of the AllergyIntolerance resources completing without error (import log or screenshot)" as $handledAllergyIntoleranceEvidence
      Then Consumer confirms each of these is accepted for "the AllergyIntolerance resources":
        | item                   | detail |
        | clinicalStatus         | active |
        | type                   |  |
        | code                   | Penicillin |
        | patient                | Patient/d174bd1a-b368-41e6-83a2-af77f… |
        | patient.reference      | Patient/d174bd1a-b368-41e6-83a2-af77f… |
        | onset[x]               |  |
        | onset[x]:onsetDateTime |  |
        | reaction               |  |
        | reaction.manifestation |  |
        | reaction.severity      |  |
      When Consumer is informed "Open Patricia JORDANA's summary in the system under test and display the AllergyIntolerance resources."
      And Consumer submits evidence of "the AllergyIntolerance resources displayed (screenshot)" as $displayedAllergyIntoleranceEvidence
      Then Consumer confirms each of these is displayed for "the AllergyIntolerance resources":
        | item                   | detail |
        | clinicalStatus         | active |
        | type                   |  |
        | code                   | Penicillin |
        | patient                | Patient/d174bd1a-b368-41e6-83a2-af77f… |
        | onset[x]               |  |
        | onset[x]:onsetDateTime |  |
        | reaction               |  |
        | reaction.manifestation |  |
        | reaction.severity      |  |

    @profile:Condition-uv-ips
    @covers:Condition.clinicalStatus @covers:Condition.category @covers:Condition.severity @covers:Condition.code
    @covers:Condition.subject @covers:Condition.subject.reference @covers:Condition.onset[x] @covers:Condition.onset[x]:onsetDateTime
    Scenario: ips-consumer-008 Condition (IPS) — the Consumer handles 8 elements and displays 7
      When Consumer submits evidence of "the import of the Condition resources completing without error (import log or screenshot)" as $handledConditionEvidence
      Then Consumer confirms each of these is accepted for "the Condition resources":
        | item                   | detail |
        | clinicalStatus         | active |
        | category               |  |
        | severity               |  |
        | code                   | Essential hypertension |
        | subject                | Patient/d174bd1a-b368-41e6-83a2-af77f… |
        | subject.reference      | Patient/d174bd1a-b368-41e6-83a2-af77f… |
        | onset[x]               | 2016-05-25 |
        | onset[x]:onsetDateTime | 2016-05-25 |
      When Consumer is informed "Open Patricia JORDANA's summary in the system under test and display the Condition resources."
      And Consumer submits evidence of "the Condition resources displayed (screenshot)" as $displayedConditionEvidence
      Then Consumer confirms each of these is displayed for "the Condition resources":
        | item                   | detail |
        | clinicalStatus         | active |
        | category               |  |
        | severity               |  |
        | code                   | Essential hypertension |
        | subject                | Patient/d174bd1a-b368-41e6-83a2-af77f… |
        | onset[x]               | 2016-05-25 |
        | onset[x]:onsetDateTime | 2016-05-25 |

    @profile:Medication-uv-ips
    @covers:Medication.code @covers:Medication.form @covers:Medication.ingredient @covers:Medication.ingredient.item[x]
    @covers:Medication.ingredient.strength
    Scenario: ips-consumer-009 Medication (IPS) — the Consumer handles 5 elements and displays 5
      When Consumer submits evidence of "the import of the Medication resources completing without error (import log or screenshot)" as $handledMedicationEvidence
      Then Consumer confirms each of these is accepted for "the Medication resources":
        | item                | detail |
        | code                |  |
        | form                |  |
        | ingredient          |  |
        | ingredient.item[x]  |  |
        | ingredient.strength |  |
      When Consumer is informed "Open Patricia JORDANA's summary in the system under test and display the Medication resources."
      And Consumer submits evidence of "the Medication resources displayed (screenshot)" as $displayedMedicationEvidence
      Then Consumer confirms each of these is displayed for "the Medication resources":
        | item                | detail |
        | code                |  |
        | form                |  |
        | ingredient          |  |
        | ingredient.item[x]  |  |
        | ingredient.strength |  |

    @profile:MedicationRequest-uv-ips
    @covers:MedicationRequest.medication[x] @covers:MedicationRequest.subject @covers:MedicationRequest.subject.reference @covers:MedicationRequest.dosageInstruction
    @covers:MedicationRequest.dosageInstruction.text @covers:MedicationRequest.dosageInstruction.timing
    Scenario: ips-consumer-010 MedicationRequest (IPS) — the Consumer handles 6 elements and displays 5
      When Consumer submits evidence of "the import of the MedicationRequest resources completing without error (import log or screenshot)" as $handledMedicationRequestEvidence
      Then Consumer confirms each of these is accepted for "the MedicationRequest resources":
        | item                     | detail |
        | medication[x]            |  |
        | subject                  |  |
        | subject.reference        |  |
        | dosageInstruction        |  |
        | dosageInstruction.text   |  |
        | dosageInstruction.timing |  |
      When Consumer is informed "Open Patricia JORDANA's summary in the system under test and display the MedicationRequest resources."
      And Consumer submits evidence of "the MedicationRequest resources displayed (screenshot)" as $displayedMedicationRequestEvidence
      Then Consumer confirms each of these is displayed for "the MedicationRequest resources":
        | item                     | detail |
        | medication[x]            |  |
        | subject                  |  |
        | dosageInstruction        |  |
        | dosageInstruction.text   |  |
        | dosageInstruction.timing |  |

    @profile:MedicationStatement-uv-ips
    @covers:MedicationStatement.medication[x] @covers:MedicationStatement.subject @covers:MedicationStatement.subject.reference @covers:MedicationStatement.effective[x]
    @covers:MedicationStatement.effective[x]:effectiveDateTime @covers:MedicationStatement.dosage @covers:MedicationStatement.dosage.text @covers:MedicationStatement.dosage.timing
    Scenario: ips-consumer-011 MedicationStatement (IPS) — the Consumer handles 8 elements and displays 7
      When Consumer submits evidence of "the import of the MedicationStatement resources completing without error (import log or screenshot)" as $handledMedicationStatementEvidence
      Then Consumer confirms each of these is accepted for "the MedicationStatement resources":
        | item                           | detail |
        | medication[x]                  | cilazapril 500 microgram tablet, 90 |
        | subject                        | Patient/d174bd1a-b368-41e6-83a2-af77f… |
        | subject.reference              | Patient/d174bd1a-b368-41e6-83a2-af77f… |
        | effective[x]                   | 2023-12-01 |
        | effective[x]:effectiveDateTime | 2023-12-01 |
        | dosage                         | Take 1 daily |
        | dosage.text                    | Take 1 daily |
        | dosage.timing                  | (present) |
      When Consumer is informed "Open Patricia JORDANA's summary in the system under test and display the MedicationStatement resources."
      And Consumer submits evidence of "the MedicationStatement resources displayed (screenshot)" as $displayedMedicationStatementEvidence
      Then Consumer confirms each of these is displayed for "the MedicationStatement resources":
        | item                           | detail |
        | medication[x]                  | cilazapril 500 microgram tablet, 90 |
        | subject                        | Patient/d174bd1a-b368-41e6-83a2-af77f… |
        | effective[x]                   | 2023-12-01 |
        | effective[x]:effectiveDateTime | 2023-12-01 |
        | dosage                         | Take 1 daily |
        | dosage.text                    | Take 1 daily |
        | dosage.timing                  | (present) |

  Rule: The recommended sections: immunizations, results, procedures, devices

    @profile:Immunization-uv-ips
    @covers:Immunization.status @covers:Immunization.vaccineCode @covers:Immunization.patient @covers:Immunization.patient.reference
    @covers:Immunization.occurrence[x] @covers:Immunization.occurrence[x]:occurrenceDateTime
    Scenario: ips-consumer-012 Immunization (IPS) — the Consumer handles 6 elements and displays 5
      When Consumer submits evidence of "the import of the Immunization resources completing without error (import log or screenshot)" as $handledImmunizationEvidence
      Then Consumer confirms each of these is accepted for "the Immunization resources":
        | item                             | detail |
        | status                           | completed |
        | vaccineCode                      | Influenza, split virus, trivalent, pr… |
        | patient                          | Patient/d174bd1a-b368-41e6-83a2-af77f… |
        | patient.reference                | Patient/d174bd1a-b368-41e6-83a2-af77f… |
        | occurrence[x]                    | 2024-04-10 |
        | occurrence[x]:occurrenceDateTime | 2024-04-10 |
      When Consumer is informed "Open Patricia JORDANA's summary in the system under test and display the Immunization resources."
      And Consumer submits evidence of "the Immunization resources displayed (screenshot)" as $displayedImmunizationEvidence
      Then Consumer confirms each of these is displayed for "the Immunization resources":
        | item                             | detail |
        | status                           | completed |
        | vaccineCode                      | Influenza, split virus, trivalent, pr… |
        | patient                          | Patient/d174bd1a-b368-41e6-83a2-af77f… |
        | occurrence[x]                    | 2024-04-10 |
        | occurrence[x]:occurrenceDateTime | 2024-04-10 |

    @profile:Observation-results-laboratory-pathology-uv-ips
    @covers:Observation.category:laboratory @covers:Observation.code @covers:Observation.subject @covers:Observation.subject.reference
    @covers:Observation.effective[x] @covers:Observation.effective[x]:effectiveDateTime @covers:Observation.performer @covers:Observation.value[x]:valueString
    @covers:Observation.value[x]:valueQuantity @covers:Observation.value[x]:valueCodeableConcept @covers:Observation.component
    Scenario: ips-consumer-013 Observation Results - Laboratory/Pathology (IPS) — the Consumer handles 11 elements and displays 10
      When Consumer submits evidence of "the import of the Observation resources of this kind completing without error (import log or screenshot)" as $handledObservationresultslaboratorypathologyEvidence
      Then Consumer confirms each of these is accepted for "the Observation resources of this kind":
        | item                           | detail |
        | category:laboratory            | laboratory |
        | code                           | Cholesterol.total/Cholesterol in HDL … |
        | subject                        | Patient/d174bd1a-b368-41e6-83a2-af77f… |
        | subject.reference              | Patient/d174bd1a-b368-41e6-83a2-af77f… |
        | effective[x]                   | 2023-10-31T15:06:00+00:00 |
        | effective[x]:effectiveDateTime | 2023-10-31T15:06:00+00:00 |
        | performer                      | PractitionerRole/75ed6f24-9a7e-4568-9… |
        | value[x]:valueString           | A combined CVD risk of which lipids i… |
        | value[x]:valueQuantity         | mmol/L |
        | value[x]:valueCodeableConcept  |  |
        | component                      |  |
      When Consumer is informed "Open Patricia JORDANA's summary in the system under test and display the Observation resources of this kind."
      And Consumer submits evidence of "the Observation resources of this kind displayed (screenshot)" as $displayedObservationresultslaboratorypathologyEvidence
      Then Consumer confirms each of these is displayed for "the Observation resources of this kind":
        | item                           | detail |
        | category:laboratory            | laboratory |
        | code                           | Cholesterol.total/Cholesterol in HDL … |
        | subject                        | Patient/d174bd1a-b368-41e6-83a2-af77f… |
        | effective[x]                   | 2023-10-31T15:06:00+00:00 |
        | effective[x]:effectiveDateTime | 2023-10-31T15:06:00+00:00 |
        | performer                      | PractitionerRole/75ed6f24-9a7e-4568-9… |
        | value[x]:valueString           | A combined CVD risk of which lipids i… |
        | value[x]:valueQuantity         | mmol/L |
        | value[x]:valueCodeableConcept  |  |
        | component                      |  |

    @profile:Observation-results-radiology-uv-ips
    @covers:Observation.category:radiology @covers:Observation.code @covers:Observation.subject @covers:Observation.subject.reference
    @covers:Observation.effective[x] @covers:Observation.effective[x]:effectiveDateTime @covers:Observation.performer @covers:Observation.value[x]:valueString
    @covers:Observation.component
    Scenario: ips-consumer-014 Observation Results - Radiology (IPS) — the Consumer handles 9 elements and displays 8
      When Consumer submits evidence of "the import of the Observation resources of this kind completing without error (import log or screenshot)" as $handledObservationresultsradiologyEvidence
      Then Consumer confirms each of these is accepted for "the Observation resources of this kind":
        | item                           | detail |
        | category:radiology             |  |
        | code                           |  |
        | subject                        |  |
        | subject.reference              |  |
        | effective[x]                   |  |
        | effective[x]:effectiveDateTime |  |
        | performer                      |  |
        | value[x]:valueString           |  |
        | component                      |  |
      When Consumer is informed "Open Patricia JORDANA's summary in the system under test and display the Observation resources of this kind."
      And Consumer submits evidence of "the Observation resources of this kind displayed (screenshot)" as $displayedObservationresultsradiologyEvidence
      Then Consumer confirms each of these is displayed for "the Observation resources of this kind":
        | item                           | detail |
        | category:radiology             |  |
        | code                           |  |
        | subject                        |  |
        | effective[x]                   |  |
        | effective[x]:effectiveDateTime |  |
        | performer                      |  |
        | value[x]:valueString           |  |
        | component                      |  |

    @profile:DiagnosticReport-uv-ips
    @covers:DiagnosticReport.code @covers:DiagnosticReport.subject @covers:DiagnosticReport.subject.reference @covers:DiagnosticReport.effective[x]
    @covers:DiagnosticReport.effective[x]:effectiveDateTime @covers:DiagnosticReport.performer @covers:DiagnosticReport.result:observation-results
    Scenario: ips-consumer-015 DiagnosticReport (IPS) — the Consumer handles 7 elements and displays 6
      When Consumer submits evidence of "the import of the DiagnosticReport resources completing without error (import log or screenshot)" as $handledDiagnosticReportEvidence
      Then Consumer confirms each of these is accepted for "the DiagnosticReport resources":
        | item                           | detail |
        | code                           |  |
        | subject                        |  |
        | subject.reference              |  |
        | effective[x]                   |  |
        | effective[x]:effectiveDateTime |  |
        | performer                      |  |
        | result:observation-results     |  |
      When Consumer is informed "Open Patricia JORDANA's summary in the system under test and display the DiagnosticReport resources."
      And Consumer submits evidence of "the DiagnosticReport resources displayed (screenshot)" as $displayedDiagnosticReportEvidence
      Then Consumer confirms each of these is displayed for "the DiagnosticReport resources":
        | item                           | detail |
        | code                           |  |
        | subject                        |  |
        | effective[x]                   |  |
        | effective[x]:effectiveDateTime |  |
        | performer                      |  |
        | result:observation-results     |  |

    @profile:Specimen-uv-ips
    @covers:Specimen.type @covers:Specimen.subject @covers:Specimen.subject.reference
    Scenario: ips-consumer-016 Specimen (IPS) — the Consumer handles 3 elements and displays 2
      When Consumer submits evidence of "the import of the Specimen resources completing without error (import log or screenshot)" as $handledSpecimenEvidence
      Then Consumer confirms each of these is accepted for "the Specimen resources":
        | item              | detail |
        | type              |  |
        | subject           |  |
        | subject.reference |  |
      When Consumer is informed "Open Patricia JORDANA's summary in the system under test and display the Specimen resources."
      And Consumer submits evidence of "the Specimen resources displayed (screenshot)" as $displayedSpecimenEvidence
      Then Consumer confirms each of these is displayed for "the Specimen resources":
        | item    | detail |
        | type    |  |
        | subject |  |

    @profile:ImagingStudy-uv-ips
    @covers:ImagingStudy.identifier @covers:ImagingStudy.subject @covers:ImagingStudy.subject.reference @covers:ImagingStudy.started
    @covers:ImagingStudy.procedureCode @covers:ImagingStudy.reasonCode @covers:ImagingStudy.series @covers:ImagingStudy.series.uid
    @covers:ImagingStudy.series.modality @covers:ImagingStudy.series.instance @covers:ImagingStudy.series.instance.uid @covers:ImagingStudy.series.instance.sopClass
    Scenario: ips-consumer-017 ImagingStudy (IPS) — the Consumer handles 12 elements and displays 11
      When Consumer submits evidence of "the import of the ImagingStudy resources completing without error (import log or screenshot)" as $handledImagingStudyEvidence
      Then Consumer confirms each of these is accepted for "the ImagingStudy resources":
        | item                     | detail |
        | identifier               |  |
        | subject                  |  |
        | subject.reference        |  |
        | started                  |  |
        | procedureCode            |  |
        | reasonCode               |  |
        | series                   |  |
        | series.uid               |  |
        | series.modality          |  |
        | series.instance          |  |
        | series.instance.uid      |  |
        | series.instance.sopClass |  |
      When Consumer is informed "Open Patricia JORDANA's summary in the system under test and display the ImagingStudy resources."
      And Consumer submits evidence of "the ImagingStudy resources displayed (screenshot)" as $displayedImagingStudyEvidence
      Then Consumer confirms each of these is displayed for "the ImagingStudy resources":
        | item                     | detail |
        | identifier               |  |
        | subject                  |  |
        | started                  |  |
        | procedureCode            |  |
        | reasonCode               |  |
        | series                   |  |
        | series.uid               |  |
        | series.modality          |  |
        | series.instance          |  |
        | series.instance.uid      |  |
        | series.instance.sopClass |  |

    @profile:Procedure-uv-ips
    @covers:Procedure.code @covers:Procedure.subject @covers:Procedure.subject.reference @covers:Procedure.performed[x]
    @covers:Procedure.performed[x]:performedDateTime
    Scenario: ips-consumer-018 Procedure (IPS) — the Consumer handles 5 elements and displays 4
      When Consumer submits evidence of "the import of the Procedure resources completing without error (import log or screenshot)" as $handledProcedureEvidence
      Then Consumer confirms each of these is accepted for "the Procedure resources":
        | item                           | detail |
        | code                           | Total hip replacement |
        | subject                        | Patient/d174bd1a-b368-41e6-83a2-af77f… |
        | subject.reference              | Patient/d174bd1a-b368-41e6-83a2-af77f… |
        | performed[x]                   | 2000-04-28 |
        | performed[x]:performedDateTime | 2000-04-28 |
      When Consumer is informed "Open Patricia JORDANA's summary in the system under test and display the Procedure resources."
      And Consumer submits evidence of "the Procedure resources displayed (screenshot)" as $displayedProcedureEvidence
      Then Consumer confirms each of these is displayed for "the Procedure resources":
        | item                           | detail |
        | code                           | Total hip replacement |
        | subject                        | Patient/d174bd1a-b368-41e6-83a2-af77f… |
        | performed[x]                   | 2000-04-28 |
        | performed[x]:performedDateTime | 2000-04-28 |

    @profile:Device-observer-uv-ips
    @covers:Device.identifier @covers:Device.manufacturer @covers:Device.modelNumber
    Scenario: ips-consumer-019 Device - Performer or Observer (IPS) — the Consumer handles 3 elements and displays 3
      When Consumer submits evidence of "the import of the Device resources completing without error (import log or screenshot)" as $handledDeviceobserverEvidence
      Then Consumer confirms each of these is accepted for "the Device resources":
        | item         | detail |
        | identifier   |  |
        | manufacturer |  |
        | modelNumber  |  |
      When Consumer is informed "Open Patricia JORDANA's summary in the system under test and display the Device resources."
      And Consumer submits evidence of "the Device resources displayed (screenshot)" as $displayedDeviceobserverEvidence
      Then Consumer confirms each of these is displayed for "the Device resources":
        | item         | detail |
        | identifier   |  |
        | manufacturer |  |
        | modelNumber  |  |

    @profile:Device-uv-ips
    @covers:Device.type
    Scenario: ips-consumer-020 Device (IPS) — the Consumer handles 1 element and displays 1
      When Consumer submits evidence of "the import of the Device resources completing without error (import log or screenshot)" as $handledDeviceEvidence
      Then Consumer confirms each of these is accepted for "the Device resources":
        | item | detail |
        | type | Hip prosthesis, device (physical object) |
      When Consumer is informed "Open Patricia JORDANA's summary in the system under test and display the Device resources."
      And Consumer submits evidence of "the Device resources displayed (screenshot)" as $displayedDeviceEvidence
      Then Consumer confirms each of these is displayed for "the Device resources":
        | item | detail |
        | type | Hip prosthesis, device (physical object) |

    @profile:DeviceUseStatement-uv-ips
    @covers:DeviceUseStatement.subject @covers:DeviceUseStatement.subject.reference @covers:DeviceUseStatement.timing[x] @covers:DeviceUseStatement.timing[x]:timingDateTime
    @covers:DeviceUseStatement.device
    Scenario: ips-consumer-021 DeviceUseStatement (IPS) — the Consumer handles 5 elements and displays 4
      When Consumer submits evidence of "the import of the DeviceUseStatement resources completing without error (import log or screenshot)" as $handledDeviceUseStatementEvidence
      Then Consumer confirms each of these is accepted for "the DeviceUseStatement resources":
        | item                     | detail |
        | subject                  | Patient/d174bd1a-b368-41e6-83a2-af77f… |
        | subject.reference        | Patient/d174bd1a-b368-41e6-83a2-af77f… |
        | timing[x]                |  |
        | timing[x]:timingDateTime |  |
        | device                   | Hip prosthesis |
      When Consumer is informed "Open Patricia JORDANA's summary in the system under test and display the DeviceUseStatement resources."
      And Consumer submits evidence of "the DeviceUseStatement resources displayed (screenshot)" as $displayedDeviceUseStatementEvidence
      Then Consumer confirms each of these is displayed for "the DeviceUseStatement resources":
        | item                     | detail |
        | subject                  | Patient/d174bd1a-b368-41e6-83a2-af77f… |
        | timing[x]                |  |
        | timing[x]:timingDateTime |  |
        | device                   | Hip prosthesis |

  Rule: The optional sections: alerts, pregnancy, social history

    @profile:Flag-alert-uv-ips
    @covers:Flag.extension:flag-priority @covers:Flag.category @covers:Flag.code @covers:Flag.subject
    @covers:Flag.subject.reference
    Scenario: ips-consumer-022 Flag - Alert (IPS) — the Consumer handles 5 elements and displays 4
      When Consumer submits evidence of "the import of the Flag resources completing without error (import log or screenshot)" as $handledFlagalertEvidence
      Then Consumer confirms each of these is accepted for "the Flag resources":
        | item                    | detail |
        | extension:flag-priority |  |
        | category                | Diet |
        | code                    | Shellfish free diet |
        | subject                 | Patient/d174bd1a-b368-41e6-83a2-af77f… |
        | subject.reference       | Patient/d174bd1a-b368-41e6-83a2-af77f… |
      When Consumer is informed "Open Patricia JORDANA's summary in the system under test and display the Flag resources."
      And Consumer submits evidence of "the Flag resources displayed (screenshot)" as $displayedFlagalertEvidence
      Then Consumer confirms each of these is displayed for "the Flag resources":
        | item                    | detail |
        | extension:flag-priority |  |
        | category                | Diet |
        | code                    | Shellfish free diet |
        | subject                 | Patient/d174bd1a-b368-41e6-83a2-af77f… |

    @profile:Observation-pregnancy-edd-uv-ips
    @covers:Observation.code @covers:Observation.subject @covers:Observation.subject.reference @covers:Observation.effective[x]
    @covers:Observation.value[x]:valueDateTime
    Scenario: ips-consumer-023 Observation Pregnancy - Expected Delivery Date (IPS) — the Consumer handles 5 elements and displays 4
      When Consumer submits evidence of "the import of the Observation resources of this kind completing without error (import log or screenshot)" as $handledObservationpregnancyeddEvidence
      Then Consumer confirms each of these is accepted for "the Observation resources of this kind":
        | item                   | detail |
        | code                   |  |
        | subject                |  |
        | subject.reference      |  |
        | effective[x]           |  |
        | value[x]:valueDateTime |  |
      When Consumer is informed "Open Patricia JORDANA's summary in the system under test and display the Observation resources of this kind."
      And Consumer submits evidence of "the Observation resources of this kind displayed (screenshot)" as $displayedObservationpregnancyeddEvidence
      Then Consumer confirms each of these is displayed for "the Observation resources of this kind":
        | item                   | detail |
        | code                   |  |
        | subject                |  |
        | effective[x]           |  |
        | value[x]:valueDateTime |  |

    @profile:Observation-pregnancy-outcome-uv-ips
    @covers:Observation.code @covers:Observation.subject @covers:Observation.subject.reference @covers:Observation.effective[x]
    @covers:Observation.value[x]:valueQuantity
    Scenario: ips-consumer-024 Observation Pregnancy - Outcome (IPS) — the Consumer handles 5 elements and displays 4
      When Consumer submits evidence of "the import of the Observation resources of this kind completing without error (import log or screenshot)" as $handledObservationpregnancyoutcomeEvidence
      Then Consumer confirms each of these is accepted for "the Observation resources of this kind":
        | item                   | detail |
        | code                   |  |
        | subject                |  |
        | subject.reference      |  |
        | effective[x]           |  |
        | value[x]:valueQuantity |  |
      When Consumer is informed "Open Patricia JORDANA's summary in the system under test and display the Observation resources of this kind."
      And Consumer submits evidence of "the Observation resources of this kind displayed (screenshot)" as $displayedObservationpregnancyoutcomeEvidence
      Then Consumer confirms each of these is displayed for "the Observation resources of this kind":
        | item                   | detail |
        | code                   |  |
        | subject                |  |
        | effective[x]           |  |
        | value[x]:valueQuantity |  |

    @profile:Observation-pregnancy-status-uv-ips
    @covers:Observation.code @covers:Observation.subject @covers:Observation.subject.reference @covers:Observation.effective[x]
    @covers:Observation.value[x]:valueCodeableConcept @covers:Observation.hasMember @covers:Observation.hasMember.reference
    Scenario: ips-consumer-025 Observation Pregnancy - Status (IPS) — the Consumer handles 7 elements and displays 6
      When Consumer submits evidence of "the import of the Observation resources of this kind completing without error (import log or screenshot)" as $handledObservationpregnancystatusEvidence
      Then Consumer confirms each of these is accepted for "the Observation resources of this kind":
        | item                          | detail |
        | code                          | Pregnancy status |
        | subject                       | Patient/d174bd1a-b368-41e6-83a2-af77f… |
        | subject.reference             | Patient/d174bd1a-b368-41e6-83a2-af77f… |
        | effective[x]                  | 2020-01-10 |
        | value[x]:valueCodeableConcept | Not Pregnant |
        | hasMember                     |  |
        | hasMember.reference           |  |
      When Consumer is informed "Open Patricia JORDANA's summary in the system under test and display the Observation resources of this kind."
      And Consumer submits evidence of "the Observation resources of this kind displayed (screenshot)" as $displayedObservationpregnancystatusEvidence
      Then Consumer confirms each of these is displayed for "the Observation resources of this kind":
        | item                          | detail |
        | code                          | Pregnancy status |
        | subject                       | Patient/d174bd1a-b368-41e6-83a2-af77f… |
        | effective[x]                  | 2020-01-10 |
        | value[x]:valueCodeableConcept | Not Pregnant |
        | hasMember                     |  |
        | hasMember.reference           |  |

  Rule: Data types used throughout

    @profile:Observation-tobaccouse-uv-ips
    @covers:Observation.code @covers:Observation.subject @covers:Observation.subject.reference @covers:Observation.effective[x]
    Scenario: ips-consumer-026 Observation Social History - Tobacco Use (IPS) — the Consumer handles 4 elements and displays 3
      When Consumer submits evidence of "the import of the Observation resources of this kind completing without error (import log or screenshot)" as $handledObservationtobaccouseEvidence
      Then Consumer confirms each of these is accepted for "the Observation resources of this kind":
        | item              | detail |
        | code              | Tobacco smoking status |
        | subject           | Patient/d174bd1a-b368-41e6-83a2-af77f… |
        | subject.reference | Patient/d174bd1a-b368-41e6-83a2-af77f… |
        | effective[x]      | 2022-10-20 |
      When Consumer is informed "Open Patricia JORDANA's summary in the system under test and display the Observation resources of this kind."
      And Consumer submits evidence of "the Observation resources of this kind displayed (screenshot)" as $displayedObservationtobaccouseEvidence
      Then Consumer confirms each of these is displayed for "the Observation resources of this kind":
        | item         | detail |
        | code         | Tobacco smoking status |
        | subject      | Patient/d174bd1a-b368-41e6-83a2-af77f… |
        | effective[x] | 2022-10-20 |

    @profile:Observation-alcoholuse-uv-ips
    @covers:Observation.code @covers:Observation.subject @covers:Observation.subject.reference @covers:Observation.effective[x]
    Scenario: ips-consumer-027 Observation Social History - Alcohol Use (IPS) — the Consumer handles 4 elements and displays 3
      When Consumer submits evidence of "the import of the Observation resources of this kind completing without error (import log or screenshot)" as $handledObservationalcoholuseEvidence
      Then Consumer confirms each of these is accepted for "the Observation resources of this kind":
        | item              | detail |
        | code              | Alcoholic drinks per day |
        | subject           | Patient/d174bd1a-b368-41e6-83a2-af77f… |
        | subject.reference | Patient/d174bd1a-b368-41e6-83a2-af77f… |
        | effective[x]      | 2016-06-22 |
      When Consumer is informed "Open Patricia JORDANA's summary in the system under test and display the Observation resources of this kind."
      And Consumer submits evidence of "the Observation resources of this kind displayed (screenshot)" as $displayedObservationalcoholuseEvidence
      Then Consumer confirms each of these is displayed for "the Observation resources of this kind":
        | item         | detail |
        | code         | Alcoholic drinks per day |
        | subject      | Patient/d174bd1a-b368-41e6-83a2-af77f… |
        | effective[x] | 2016-06-22 |

    @profile:CodeableConcept-uv-ips
    @covers:CodeableConcept.coding @covers:CodeableConcept.text
    Scenario: ips-consumer-028 Codeable Concept (IPS) — the Consumer handles 2 elements and displays 1
      When Consumer submits evidence of "the import of every CodeableConcept in the document completing without error (import log or screenshot)" as $handledCodeableConceptEvidence
      Then Consumer confirms each of these is accepted for "every CodeableConcept in the document":
        | item   | detail |
        | coding |  |
        | text   |  |
      When Consumer is informed "Open Patricia JORDANA's summary in the system under test and display every CodeableConcept in the document."
      And Consumer submits evidence of "every CodeableConcept in the document displayed (screenshot)" as $displayedCodeableConceptEvidence
      Then Consumer confirms each of these is displayed for "every CodeableConcept in the document":
        | item | detail |
        | text |  |

    @profile:Coding-uv-ips
    @covers:Coding.system @covers:Coding.code
    Scenario: ips-consumer-029 Coding with translations — the Consumer handles 2 elements
      When Consumer submits evidence of "the import of every Coding in the document completing without error (import log or screenshot)" as $handledCodingEvidence
      Then Consumer confirms each of these is accepted for "every Coding in the document":
        | item   | detail |
        | system |  |
        | code   |  |

  Rule: Documents with missing information are handled, not rejected

    @profile:Composition-uv-ips
    @covers:Composition.section:sectionProblems.emptyReason @covers:Composition.section:sectionAllergies.emptyReason @covers:Composition.section:sectionMedications.emptyReason
    Scenario: ips-consumer-900 Required sections with an emptyReason and a minimal document are accepted
      When Tester gets "https://hl7.org/fhir/uv/ips/Bundle-bundle-no-info-required-sections.json" as $ipsNoInfo
      And Consumer is informed "Import this IPS, whose problems, allergies and medications sections carry an emptyReason instead of entries." with $ipsNoInfo
      And Consumer submits evidence of "the three required sections shown with no information (screenshot)" as $noInfoEvidence
      Then Consumer confirms each of these is accepted for "a document whose required sections carry an emptyReason":
        | item                                   | detail                  |
        | section:sectionProblems.emptyReason    | shown as no information |
        | section:sectionAllergies.emptyReason   | shown as no information |
        | section:sectionMedications.emptyReason | shown as no information |
      When Tester gets "https://hl7.org/fhir/uv/ips/Bundle-bundle-minimal.json" as $ipsMinimal
      And Consumer is informed "Import this minimal IPS (required sections only, no optional elements)." with $ipsMinimal
      And Consumer submits evidence of "the minimal document imported without error (import log or screenshot)" as $minimalEvidence
      Then Consumer confirms each of these is accepted for "the minimal document":
        | item         | detail                 |
        | the document | imported without error |

  Rule: A Consumer that is a FHIR server is driven directly

    Scenario: ips-consumer-950 The document is accepted over the FHIR API
      # For a Consumer exposing a FHIR endpoint: declare it with an endpoint in the
      # Background ("Consumer is the system under test at ...") and the test bed
      # submits the document itself instead of asking a tester to import it.
      When Tester posts to Consumer at "/Bundle" with body $ips
      Then $response.status should be one of "200, 201"
