# GENERATED by app/scripts/ips-obligations.mjs from hl7.fhir.uv.ips 2.0.1. Edit the generator, not this file.
#
# One scenario per profile that carries Creator obligations. Each scenario
# declares the elements it covers (@covers:) and asserts every one of them on
# the document the Creator produced for the reference patient. Which form the
# assertion takes follows the obligation and the reference data:
#   SHALL:populate                     present in every instance
#   SHALL:populate-if-known            present wherever the reference data has it
#   SHALL/SHOULD:able-to-populate      present, or attested by the tester when the
#                                      reference data cannot exercise it
#   MAY:able-to-populate               logged, not asserted
# Every test case asks for the document once — ITB runs each scenario as its own
# test case. An IPS Server is tested without the paste by ips-server.feature.
@lang:itb-core-en@^2 @dialect:fhir-validator@^2 @actor:Creator @spec:hl7.fhir.uv.ips@2.0.1
Feature: IPS Creator — obligations of hl7.fhir.uv.ips 2.0.1
  An IPS Creator actor is a system which produces/assembles/creates an IPS document.
  The reference patient is the IG's own all-sections example, Patricia JORDANA
  (identifier ABC1234): every element with a Creator obligation that the
  example carries must appear in the document the system produces for her.

  Background:
    Given Creator is the system under test
    And FHIRValidator is a fhir-validator at "http://fhir-validator:8081"
    And FHIRValidator is loaded with package "hl7.fhir.uv.ips#2.0.1"
    And Creator is informed "Load the reference patient Patricia JORDANA (identifier ABC1234) into your system from https://hl7.org/fhir/uv/ips/Bundle-bundle-ips-all-sections.json, then export her International Patient Summary as a FHIR document Bundle."
    And Creator is asked for $ips with "Paste the exported IPS Bundle (JSON)"
    And $ips is a FHIR resource

  Rule: The document as a whole conforms

    @profile:Bundle-uv-ips
    Scenario: ips-creator-000 The exported document is a valid IPS Bundle
      Then $ips should conform to "http://hl7.org/fhir/uv/ips/StructureDefinition/Bundle-uv-ips" ignoring slicing errors
      And $ips at "Bundle.type" should be "document"

  Rule: The document: Bundle and Composition

    @profile:Bundle-uv-ips
    @covers:Bundle.identifier @covers:Bundle.timestamp @covers:Bundle.entry:composition
    Scenario: ips-creator-001 Bundle (IPS) — the Creator populates identifier, timestamp, entry:composition
      # Bundle.identifier (SHALL:populate)
      Then $ips at "Bundle.identifier.exists()" should be true
      # Bundle.timestamp (SHALL:populate)
      Then $ips at "Bundle.timestamp.exists()" should be true
      # Bundle.entry:composition (SHALL:populate)
      Then $ips at "Bundle.entry.where(resource.ofType(Composition).exists()).exists()" should be true

    @profile:Composition-uv-ips
    @covers:Composition.meta.profile @covers:Composition.text @covers:Composition.identifier @covers:Composition.status
    @covers:Composition.type @covers:Composition.subject @covers:Composition.subject.reference @covers:Composition.date
    @covers:Composition.author @covers:Composition.title @covers:Composition.attester @covers:Composition.attester.mode
    @covers:Composition.attester.time @covers:Composition.attester.party @covers:Composition.custodian @covers:Composition.event:careProvisioningEvent
    @covers:Composition.event:careProvisioningEvent.code @covers:Composition.event:careProvisioningEvent.period @covers:Composition.section.title @covers:Composition.section.text
    @covers:Composition.section:sectionProblems @covers:Composition.section:sectionProblems.title @covers:Composition.section:sectionProblems.text @covers:Composition.section:sectionProblems.entry:problem
    @covers:Composition.section:sectionProblems.emptyReason @covers:Composition.section:sectionAllergies @covers:Composition.section:sectionAllergies.title @covers:Composition.section:sectionAllergies.text
    @covers:Composition.section:sectionAllergies.entry:allergyOrIntolerance @covers:Composition.section:sectionAllergies.emptyReason @covers:Composition.section:sectionMedications @covers:Composition.section:sectionMedications.title
    @covers:Composition.section:sectionMedications.text @covers:Composition.section:sectionMedications.entry:medicationStatementOrRequest @covers:Composition.section:sectionMedications.emptyReason @covers:Composition.section:sectionImmunizations
    @covers:Composition.section:sectionImmunizations.title @covers:Composition.section:sectionImmunizations.text @covers:Composition.section:sectionImmunizations.entry:immunization @covers:Composition.section:sectionResults
    @covers:Composition.section:sectionResults.title @covers:Composition.section:sectionResults.text @covers:Composition.section:sectionResults.entry:results-observation-laboratory-pathology @covers:Composition.section:sectionResults.entry:results-observation-radiology
    @covers:Composition.section:sectionProceduresHx @covers:Composition.section:sectionProceduresHx.title @covers:Composition.section:sectionProceduresHx.text @covers:Composition.section:sectionProceduresHx.entry:procedure
    @covers:Composition.section:sectionMedicalDevices @covers:Composition.section:sectionMedicalDevices.title @covers:Composition.section:sectionMedicalDevices.text @covers:Composition.section:sectionMedicalDevices.entry:deviceStatement
    @covers:Composition.section:sectionAdvanceDirectives.title @covers:Composition.section:sectionAdvanceDirectives.text @covers:Composition.section:sectionAlerts.title @covers:Composition.section:sectionAlerts.text
    @covers:Composition.section:sectionFunctionalStatus.title @covers:Composition.section:sectionFunctionalStatus.text @covers:Composition.section:sectionPastProblems.title @covers:Composition.section:sectionPastProblems.text
    @covers:Composition.section:sectionPregnancyHx.title @covers:Composition.section:sectionPregnancyHx.text @covers:Composition.section:sectionPatientStory.title @covers:Composition.section:sectionPatientStory.text
    @covers:Composition.section:sectionPlanOfCare.title @covers:Composition.section:sectionPlanOfCare.text @covers:Composition.section:sectionSocialHistory.title @covers:Composition.section:sectionSocialHistory.text
    @covers:Composition.section:sectionVitalSigns.title @covers:Composition.section:sectionVitalSigns.text
    Scenario: ips-creator-002 Composition (IPS) — the Creator populates status, type, subject, subject.reference and more; 23 elements when known
      # Instances: Bundle.entry.resource.ofType(Composition)
      # Composition.text (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Composition).all(text.exists())" should be true
      # Composition.identifier (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Composition).all(identifier.exists())" should be true
      # Composition.status (SHALL:populate)
      Then $ips at "Bundle.entry.resource.ofType(Composition).all(status.exists())" should be true
      # Composition.type (SHALL:populate)
      Then $ips at "Bundle.entry.resource.ofType(Composition).all(type.exists())" should be true
      # Composition.subject (SHALL:populate)
      Then $ips at "Bundle.entry.resource.ofType(Composition).all(subject.exists())" should be true
      # Composition.subject.reference (SHALL:populate)
      Then $ips at "Bundle.entry.resource.ofType(Composition).subject.all(reference.exists())" should be true
      # Composition.date (SHALL:populate)
      Then $ips at "Bundle.entry.resource.ofType(Composition).all(date.exists())" should be true
      # Composition.author (SHALL:populate)
      Then $ips at "Bundle.entry.resource.ofType(Composition).all(author.exists())" should be true
      # Composition.title (SHALL:populate)
      Then $ips at "Bundle.entry.resource.ofType(Composition).all(title.exists())" should be true
      # Composition.attester (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Composition).all(attester.exists())" should be true
      # Composition.attester.mode (SHALL:populate)
      Then $ips at "Bundle.entry.resource.ofType(Composition).attester.all(mode.exists())" should be true
      # Composition.attester.time (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Composition).attester.all(time.exists())" should be true
      # Composition.attester.party (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Composition).attester.all(party.exists())" should be true
      # Composition.custodian (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Composition).all(custodian.exists())" should be true
      # Composition.event:careProvisioningEvent (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Composition).all(event.where(code.coding.where(system='http://terminology.hl7.org/CodeSystem/v3-ActClass' and code='PCPR').exists()).exists())" should be true
      # Composition.event:careProvisioningEvent.code (SHALL:populate)
      Then $ips at "Bundle.entry.resource.ofType(Composition).event.where(code.coding.where(system='http://terminology.hl7.org/CodeSystem/v3-ActClass' and code='PCPR').exists()).all(code.exists())" should be true
      # Composition.event:careProvisioningEvent.period (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Composition).event.where(code.coding.where(system='http://terminology.hl7.org/CodeSystem/v3-ActClass' and code='PCPR').exists()).all(period.exists())" should be true
      # Composition.section.title (SHALL:populate)
      Then $ips at "Bundle.entry.resource.ofType(Composition).section.all(title.exists())" should be true
      # Composition.section.text (SHALL:populate)
      Then $ips at "Bundle.entry.resource.ofType(Composition).section.all(text.exists())" should be true
      # Composition.section:sectionProblems (SHALL:populate)
      Then $ips at "Bundle.entry.resource.ofType(Composition).all(section.where(code.coding.where(system='http://loinc.org' and code='11450-4').exists()).exists())" should be true
      # Composition.section:sectionProblems.title (SHALL:populate)
      Then $ips at "Bundle.entry.resource.ofType(Composition).section.where(code.coding.where(system='http://loinc.org' and code='11450-4').exists()).all(title.exists())" should be true
      # Composition.section:sectionProblems.text (SHALL:populate)
      Then $ips at "Bundle.entry.resource.ofType(Composition).section.where(code.coding.where(system='http://loinc.org' and code='11450-4').exists()).all(text.exists())" should be true
      # Composition.section:sectionProblems.entry:problem (SHALL:able-to-populate, SHOULD:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Composition).section.where(code.coding.where(system='http://loinc.org' and code='11450-4').exists()).all(entry.where(reference.contains('Condition') or reference.exists()).exists()) and Bundle.entry.resource.ofType(Condition).exists()" should be true
      # Composition.section:sectionAllergies (SHALL:populate)
      Then $ips at "Bundle.entry.resource.ofType(Composition).all(section.where(code.coding.where(system='http://loinc.org' and code='48765-2').exists()).exists())" should be true
      # Composition.section:sectionAllergies.title (SHALL:populate)
      Then $ips at "Bundle.entry.resource.ofType(Composition).section.where(code.coding.where(system='http://loinc.org' and code='48765-2').exists()).all(title.exists())" should be true
      # Composition.section:sectionAllergies.text (SHALL:populate)
      Then $ips at "Bundle.entry.resource.ofType(Composition).section.where(code.coding.where(system='http://loinc.org' and code='48765-2').exists()).all(text.exists())" should be true
      # Composition.section:sectionAllergies.entry:allergyOrIntolerance (SHALL:able-to-populate, SHOULD:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Composition).section.where(code.coding.where(system='http://loinc.org' and code='48765-2').exists()).all(entry.where(reference.contains('AllergyIntolerance') or reference.exists()).exists()) and Bundle.entry.resource.ofType(AllergyIntolerance).exists()" should be true
      # Composition.section:sectionMedications (SHALL:populate)
      Then $ips at "Bundle.entry.resource.ofType(Composition).all(section.where(code.coding.where(system='http://loinc.org' and code='10160-0').exists()).exists())" should be true
      # Composition.section:sectionMedications.title (SHALL:populate)
      Then $ips at "Bundle.entry.resource.ofType(Composition).section.where(code.coding.where(system='http://loinc.org' and code='10160-0').exists()).all(title.exists())" should be true
      # Composition.section:sectionMedications.text (SHALL:populate)
      Then $ips at "Bundle.entry.resource.ofType(Composition).section.where(code.coding.where(system='http://loinc.org' and code='10160-0').exists()).all(text.exists())" should be true
      # Composition.section:sectionMedications.entry:medicationStatementOrRequest (SHALL:able-to-populate, SHOULD:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Composition).section.where(code.coding.where(system='http://loinc.org' and code='10160-0').exists()).all(entry.where(reference.contains('MedicationStatement') or reference.exists()).exists()) and Bundle.entry.resource.ofType(MedicationStatement).exists()" should be true
      # Composition.section:sectionImmunizations (SHOULD:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Composition).all(section.where(code.coding.where(system='http://loinc.org' and code='11369-6').exists()).exists())" should be true
      # Composition.section:sectionImmunizations.title (SHALL:populate)
      Then $ips at "Bundle.entry.resource.ofType(Composition).section.where(code.coding.where(system='http://loinc.org' and code='11369-6').exists()).all(title.exists())" should be true
      # Composition.section:sectionImmunizations.text (SHALL:populate)
      Then $ips at "Bundle.entry.resource.ofType(Composition).section.where(code.coding.where(system='http://loinc.org' and code='11369-6').exists()).all(text.exists())" should be true
      # Composition.section:sectionImmunizations.entry:immunization (SHOULD:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Composition).section.where(code.coding.where(system='http://loinc.org' and code='11369-6').exists()).all(entry.where(reference.contains('Immunization') or reference.exists()).exists()) and Bundle.entry.resource.ofType(Immunization).exists()" should be true
      # Composition.section:sectionResults (SHOULD:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Composition).all(section.where(code.coding.where(system='http://loinc.org' and code='30954-2').exists()).exists())" should be true
      # Composition.section:sectionResults.title (SHALL:populate)
      Then $ips at "Bundle.entry.resource.ofType(Composition).section.where(code.coding.where(system='http://loinc.org' and code='30954-2').exists()).all(title.exists())" should be true
      # Composition.section:sectionResults.text (SHALL:populate)
      Then $ips at "Bundle.entry.resource.ofType(Composition).section.where(code.coding.where(system='http://loinc.org' and code='30954-2').exists()).all(text.exists())" should be true
      # Composition.section:sectionResults.entry:results-observation-laboratory-pathology (SHOULD:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Composition).section.where(code.coding.where(system='http://loinc.org' and code='30954-2').exists()).all(entry.where(reference.contains('Observation') or reference.exists()).exists()) and Bundle.entry.resource.ofType(Observation).exists()" should be true
      # Composition.section:sectionResults.entry:results-observation-radiology (SHOULD:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Composition).section.where(code.coding.where(system='http://loinc.org' and code='30954-2').exists()).all(entry.where(reference.contains('Observation') or reference.exists()).exists()) and Bundle.entry.resource.ofType(Observation).exists()" should be true
      # Composition.section:sectionProceduresHx (SHOULD:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Composition).all(section.where(code.coding.where(system='http://loinc.org' and code='47519-4').exists()).exists())" should be true
      # Composition.section:sectionProceduresHx.title (SHALL:populate)
      Then $ips at "Bundle.entry.resource.ofType(Composition).section.where(code.coding.where(system='http://loinc.org' and code='47519-4').exists()).all(title.exists())" should be true
      # Composition.section:sectionProceduresHx.text (SHALL:populate)
      Then $ips at "Bundle.entry.resource.ofType(Composition).section.where(code.coding.where(system='http://loinc.org' and code='47519-4').exists()).all(text.exists())" should be true
      # Composition.section:sectionProceduresHx.entry:procedure (SHOULD:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Composition).section.where(code.coding.where(system='http://loinc.org' and code='47519-4').exists()).all(entry.where(reference.contains('Procedure') or reference.exists()).exists()) and Bundle.entry.resource.ofType(Procedure).exists()" should be true
      # Composition.section:sectionMedicalDevices (SHOULD:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Composition).all(section.where(code.coding.where(system='http://loinc.org' and code='46264-8').exists()).exists())" should be true
      # Composition.section:sectionMedicalDevices.title (SHALL:populate)
      Then $ips at "Bundle.entry.resource.ofType(Composition).section.where(code.coding.where(system='http://loinc.org' and code='46264-8').exists()).all(title.exists())" should be true
      # Composition.section:sectionMedicalDevices.text (SHALL:populate)
      Then $ips at "Bundle.entry.resource.ofType(Composition).section.where(code.coding.where(system='http://loinc.org' and code='46264-8').exists()).all(text.exists())" should be true
      # Composition.section:sectionMedicalDevices.entry:deviceStatement (SHOULD:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Composition).section.where(code.coding.where(system='http://loinc.org' and code='46264-8').exists()).all(entry.where(reference.contains('DeviceUseStatement') or reference.exists()).exists()) and Bundle.entry.resource.ofType(DeviceUseStatement).exists()" should be true
      # Composition.section:sectionAdvanceDirectives.title (SHALL:populate)
      Then $ips at "Bundle.entry.resource.ofType(Composition).section.where(code.coding.where(system='http://loinc.org' and code='42348-3').exists()).all(title.exists())" should be true
      # Composition.section:sectionAdvanceDirectives.text (SHALL:populate)
      Then $ips at "Bundle.entry.resource.ofType(Composition).section.where(code.coding.where(system='http://loinc.org' and code='42348-3').exists()).all(text.exists())" should be true
      # Composition.section:sectionAlerts.title (SHALL:populate)
      Then $ips at "Bundle.entry.resource.ofType(Composition).section.where(code.coding.where(system='http://loinc.org' and code='104605-1').exists()).all(title.exists())" should be true
      # Composition.section:sectionAlerts.text (SHALL:populate)
      Then $ips at "Bundle.entry.resource.ofType(Composition).section.where(code.coding.where(system='http://loinc.org' and code='104605-1').exists()).all(text.exists())" should be true
      # Composition.section:sectionFunctionalStatus.title (SHALL:populate)
      Then $ips at "Bundle.entry.resource.ofType(Composition).section.where(code.coding.where(system='http://loinc.org' and code='47420-5').exists()).all(title.exists())" should be true
      # Composition.section:sectionFunctionalStatus.text (SHALL:populate)
      Then $ips at "Bundle.entry.resource.ofType(Composition).section.where(code.coding.where(system='http://loinc.org' and code='47420-5').exists()).all(text.exists())" should be true
      # Composition.section:sectionPastProblems.title (SHALL:populate)
      Then $ips at "Bundle.entry.resource.ofType(Composition).section.where(code.coding.where(system='http://loinc.org' and code='11348-0').exists()).all(title.exists())" should be true
      # Composition.section:sectionPastProblems.text (SHALL:populate)
      Then $ips at "Bundle.entry.resource.ofType(Composition).section.where(code.coding.where(system='http://loinc.org' and code='11348-0').exists()).all(text.exists())" should be true
      # Composition.section:sectionPregnancyHx.title (SHALL:populate)
      Then $ips at "Bundle.entry.resource.ofType(Composition).section.where(code.coding.where(system='http://loinc.org' and code='10162-6').exists()).all(title.exists())" should be true
      # Composition.section:sectionPregnancyHx.text (SHALL:populate)
      Then $ips at "Bundle.entry.resource.ofType(Composition).section.where(code.coding.where(system='http://loinc.org' and code='10162-6').exists()).all(text.exists())" should be true
      # Composition.section:sectionPatientStory.title (SHALL:populate)
      Then $ips at "Bundle.entry.resource.ofType(Composition).section.where(code.coding.where(system='http://loinc.org' and code='81338-6').exists()).all(title.exists())" should be true
      # Composition.section:sectionPatientStory.text (SHALL:populate)
      Then $ips at "Bundle.entry.resource.ofType(Composition).section.where(code.coding.where(system='http://loinc.org' and code='81338-6').exists()).all(text.exists())" should be true
      # Composition.section:sectionPlanOfCare.title (SHALL:populate)
      Then $ips at "Bundle.entry.resource.ofType(Composition).section.where(code.coding.where(system='http://loinc.org' and code='18776-5').exists()).all(title.exists())" should be true
      # Composition.section:sectionPlanOfCare.text (SHALL:populate)
      Then $ips at "Bundle.entry.resource.ofType(Composition).section.where(code.coding.where(system='http://loinc.org' and code='18776-5').exists()).all(text.exists())" should be true
      # Composition.section:sectionSocialHistory.title (SHALL:populate)
      Then $ips at "Bundle.entry.resource.ofType(Composition).section.where(code.coding.where(system='http://loinc.org' and code='29762-2').exists()).all(title.exists())" should be true
      # Composition.section:sectionSocialHistory.text (SHALL:populate)
      Then $ips at "Bundle.entry.resource.ofType(Composition).section.where(code.coding.where(system='http://loinc.org' and code='29762-2').exists()).all(text.exists())" should be true
      # Composition.section:sectionVitalSigns.title (SHALL:populate)
      Then $ips at "Bundle.entry.resource.ofType(Composition).section.where(code.coding.where(system='http://loinc.org' and code='8716-3').exists()).all(title.exists())" should be true
      # Composition.section:sectionVitalSigns.text (SHALL:populate)
      Then $ips at "Bundle.entry.resource.ofType(Composition).section.where(code.coding.where(system='http://loinc.org' and code='8716-3').exists()).all(text.exists())" should be true
      # The reference data does not exercise these; the Creator attests the capability.
      When Creator is asked for $canPopulate with "The reference patient has no data for these Composition elements. Can your system populate each of them when the information is known: [section:sectionProblems.emptyReason], [section:sectionAllergies.emptyReason], [section:sectionMedications.emptyReason]? Answer yes, or list the ones it cannot."
      Then $canPopulate should be "yes"
      And log "Composition.meta.profile MAY be populated — recorded, not asserted"

  Rule: The people and organisations

    @profile:Patient-uv-ips
    @covers:Patient.identifier @covers:Patient.name @covers:Patient.name.use @covers:Patient.name.text
    @covers:Patient.name.family @covers:Patient.name.given @covers:Patient.telecom @covers:Patient.gender
    @covers:Patient.birthDate @covers:Patient.address @covers:Patient.generalPractitioner
    Scenario: ips-creator-003 Patient (IPS) — the Creator populates name; 10 elements when known
      # Instances: Bundle.entry.resource.ofType(Patient)
      # Patient.identifier (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Patient).all(identifier.exists())" should be true
      # Patient.name (SHALL:populate)
      Then $ips at "Bundle.entry.resource.ofType(Patient).all(name.exists())" should be true
      # Patient.name.use (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Patient).name.all(use.exists())" should be true
      # Patient.name.family (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Patient).name.all(family.exists())" should be true
      # Patient.name.given (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Patient).name.all(given.exists())" should be true
      # Patient.telecom (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Patient).all(telecom.exists())" should be true
      # Patient.gender (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Patient).all(gender.exists())" should be true
      # Patient.birthDate (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Patient).all(birthDate.exists())" should be true
      # Patient.address (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Patient).all(address.exists())" should be true
      # The reference data does not exercise these; the Creator attests the capability.
      When Creator is asked for $canPopulate with "The reference patient has no data for these Patient elements. Can your system populate each of them when the information is known: [name.text], [generalPractitioner]? Answer yes, or list the ones it cannot."
      Then $canPopulate should be "yes"

    @profile:Practitioner-uv-ips
    @covers:Practitioner.name @covers:Practitioner.name.family @covers:Practitioner.name.given @covers:Practitioner.telecom
    @covers:Practitioner.address
    Scenario: ips-creator-004 Practitioner (IPS) — the Creator populates 5 elements when known
      # Instances: Bundle.entry.resource.ofType(Practitioner)
      # Practitioner.name (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Practitioner).all(name.exists())" should be true
      # Practitioner.name.family (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Practitioner).name.all(family.exists())" should be true
      # Practitioner.name.given (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Practitioner).name.all(given.exists())" should be true
      # Practitioner.telecom (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Practitioner).all(telecom.exists())" should be true
      # The reference data does not exercise these; the Creator attests the capability.
      When Creator is asked for $canPopulate with "The reference patient has no data for these Practitioner elements. Can your system populate each of them when the information is known: [address]? Answer yes, or list the ones it cannot."
      Then $canPopulate should be "yes"

    @profile:PractitionerRole-uv-ips
    @covers:PractitionerRole.organization
    Scenario: ips-creator-005 PractitionerRole (IPS) — the Creator populates 1 element when known
      # Instances: Bundle.entry.resource.ofType(PractitionerRole)
      # The reference data does not exercise these; the Creator attests the capability.
      When Creator is asked for $canPopulate with "The reference patient has no data for these PractitionerRole elements. Can your system populate each of them when the information is known: [organization]? Answer yes, or list the ones it cannot."
      Then $canPopulate should be "yes"

    @profile:Organization-uv-ips
    @covers:Organization.name @covers:Organization.telecom @covers:Organization.address
    Scenario: ips-creator-006 Organization (IPS) — the Creator populates 3 elements when known
      # Instances: Bundle.entry.resource.ofType(Organization)
      # Organization.name (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Organization).all(name.exists())" should be true
      # The reference data does not exercise these; the Creator attests the capability.
      When Creator is asked for $canPopulate with "The reference patient has no data for these Organization elements. Can your system populate each of them when the information is known: [telecom], [address]? Answer yes, or list the ones it cannot."
      Then $canPopulate should be "yes"

  Rule: The required sections: problems, allergies, medications

    @profile:AllergyIntolerance-uv-ips
    @covers:AllergyIntolerance.clinicalStatus @covers:AllergyIntolerance.type @covers:AllergyIntolerance.code @covers:AllergyIntolerance.patient
    @covers:AllergyIntolerance.patient.reference @covers:AllergyIntolerance.onset[x] @covers:AllergyIntolerance.onset[x]:onsetDateTime @covers:AllergyIntolerance.reaction
    @covers:AllergyIntolerance.reaction.manifestation @covers:AllergyIntolerance.reaction.severity
    Scenario: ips-creator-007 AllergyIntolerance (IPS) — the Creator populates 9 elements when known
      # Instances: Bundle.entry.resource.ofType(AllergyIntolerance)
      # AllergyIntolerance.clinicalStatus (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(AllergyIntolerance).all(clinicalStatus.exists())" should be true
      # AllergyIntolerance.code (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(AllergyIntolerance).all(code.exists())" should be true
      # AllergyIntolerance.patient (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(AllergyIntolerance).all(patient.exists())" should be true
      # AllergyIntolerance.patient.reference (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(AllergyIntolerance).patient.all(reference.exists())" should be true
      # The reference data does not exercise these; the Creator attests the capability.
      When Creator is asked for $canPopulate with "The reference patient has no data for these AllergyIntolerance elements. Can your system populate each of them when the information is known: [type], [onset[x]], [onset[x]:onsetDateTime], [reaction], [reaction.manifestation], [reaction.severity]? Answer yes, or list the ones it cannot."
      Then $canPopulate should be "yes"

    @profile:Condition-uv-ips
    @covers:Condition.clinicalStatus @covers:Condition.category @covers:Condition.severity @covers:Condition.code
    @covers:Condition.subject @covers:Condition.subject.reference @covers:Condition.onset[x] @covers:Condition.onset[x]:onsetDateTime
    Scenario: ips-creator-008 Condition (IPS) — the Creator populates 7 elements when known
      # Instances: Bundle.entry.resource.ofType(Condition)
      # Condition.clinicalStatus (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Condition).all(clinicalStatus.exists())" should be true
      # Condition.code (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Condition).all(code.exists())" should be true
      # Condition.subject (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Condition).all(subject.exists())" should be true
      # Condition.subject.reference (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Condition).subject.all(reference.exists())" should be true
      # Condition.onset[x] (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Condition).all(onset.exists())" should be true
      # Condition.onset[x]:onsetDateTime (SHOULD:able-to-populate)
      Then $ips at "Bundle.entry.resource.ofType(Condition).all(onset.ofType(dateTime).exists())" should be true
      # The reference data does not exercise these; the Creator attests the capability.
      When Creator is asked for $canPopulate with "The reference patient has no data for these Condition elements. Can your system populate each of them when the information is known: [category], [severity]? Answer yes, or list the ones it cannot."
      Then $canPopulate should be "yes"

    @profile:Medication-uv-ips
    @covers:Medication.code @covers:Medication.form @covers:Medication.ingredient @covers:Medication.ingredient.item[x]
    @covers:Medication.ingredient.strength
    Scenario: ips-creator-009 Medication (IPS) — the Creator populates 5 elements when known
      # Instances: Bundle.entry.resource.ofType(Medication)
      # The reference data does not exercise these; the Creator attests the capability.
      When Creator is asked for $canPopulate with "The reference patient has no data for these Medication elements. Can your system populate each of them when the information is known: [code], [form], [ingredient], [ingredient.item[x]], [ingredient.strength]? Answer yes, or list the ones it cannot."
      Then $canPopulate should be "yes"

    @profile:MedicationRequest-uv-ips
    @covers:MedicationRequest.medication[x] @covers:MedicationRequest.subject @covers:MedicationRequest.subject.reference @covers:MedicationRequest.dosageInstruction
    @covers:MedicationRequest.dosageInstruction.text @covers:MedicationRequest.dosageInstruction.timing
    Scenario: ips-creator-010 MedicationRequest (IPS) — the Creator populates 6 elements when known
      # Instances: Bundle.entry.resource.ofType(MedicationRequest)
      # The reference data does not exercise these; the Creator attests the capability.
      When Creator is asked for $canPopulate with "The reference patient has no data for these MedicationRequest elements. Can your system populate each of them when the information is known: [medication[x]], [subject], [subject.reference], [dosageInstruction], [dosageInstruction.text], [dosageInstruction.timing]? Answer yes, or list the ones it cannot."
      Then $canPopulate should be "yes"

    @profile:MedicationStatement-uv-ips
    @covers:MedicationStatement.medication[x] @covers:MedicationStatement.subject @covers:MedicationStatement.subject.reference @covers:MedicationStatement.effective[x]
    @covers:MedicationStatement.effective[x]:effectiveDateTime @covers:MedicationStatement.dosage @covers:MedicationStatement.dosage.text @covers:MedicationStatement.dosage.timing
    Scenario: ips-creator-011 MedicationStatement (IPS) — the Creator populates 7 elements when known
      # Instances: Bundle.entry.resource.ofType(MedicationStatement)
      # MedicationStatement.medication[x] (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(MedicationStatement).all(medication.exists())" should be true
      # MedicationStatement.subject (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(MedicationStatement).all(subject.exists())" should be true
      # MedicationStatement.subject.reference (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(MedicationStatement).subject.all(reference.exists())" should be true
      # MedicationStatement.effective[x] (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(MedicationStatement).all(effective.exists())" should be true
      # MedicationStatement.effective[x]:effectiveDateTime (SHOULD:able-to-populate)
      Then $ips at "Bundle.entry.resource.ofType(MedicationStatement).all(effective.ofType(dateTime).exists())" should be true
      # MedicationStatement.dosage (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(MedicationStatement).all(dosage.exists())" should be true
      # MedicationStatement.dosage.text (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(MedicationStatement).dosage.all(text.exists())" should be true
      # MedicationStatement.dosage.timing (SHALL:populate-if-known) — the reference data carries it on some instances
      Then $ips at "Bundle.entry.resource.ofType(MedicationStatement).dosage.where(timing.exists()).exists()" should be true

  Rule: The recommended sections: immunizations, results, procedures, devices

    @profile:Immunization-uv-ips
    @covers:Immunization.status @covers:Immunization.vaccineCode @covers:Immunization.patient @covers:Immunization.patient.reference
    @covers:Immunization.occurrence[x] @covers:Immunization.occurrence[x]:occurrenceDateTime
    Scenario: ips-creator-012 Immunization (IPS) — the Creator populates 5 elements when known
      # Instances: Bundle.entry.resource.ofType(Immunization)
      # Immunization.status (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Immunization).all(status.exists())" should be true
      # Immunization.vaccineCode (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Immunization).all(vaccineCode.exists())" should be true
      # Immunization.patient (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Immunization).all(patient.exists())" should be true
      # Immunization.patient.reference (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Immunization).patient.all(reference.exists())" should be true
      # Immunization.occurrence[x] (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Immunization).all(occurrence.exists())" should be true
      # Immunization.occurrence[x]:occurrenceDateTime (SHOULD:able-to-populate)
      Then $ips at "Bundle.entry.resource.ofType(Immunization).all(occurrence.ofType(dateTime).exists())" should be true

    @profile:Observation-results-laboratory-pathology-uv-ips
    @covers:Observation.category:laboratory @covers:Observation.code @covers:Observation.subject @covers:Observation.subject.reference
    @covers:Observation.effective[x] @covers:Observation.effective[x]:effectiveDateTime @covers:Observation.performer @covers:Observation.value[x]:valueString
    @covers:Observation.value[x]:valueQuantity @covers:Observation.value[x]:valueCodeableConcept @covers:Observation.component
    Scenario: ips-creator-013 Observation Results - Laboratory/Pathology (IPS) — the Creator populates 10 elements when known
      # Instances: Bundle.entry.resource.ofType(Observation).where(category.coding.where(code='laboratory').exists())
      # Observation.category:laboratory (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Observation).where(category.coding.where(code='laboratory').exists()).all(category.where(coding.where(system='http://terminology.hl7.org/CodeSystem/observation-category' and code='laboratory').exists()).exists())" should be true
      # Observation.code (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Observation).where(category.coding.where(code='laboratory').exists()).all(code.exists())" should be true
      # Observation.subject (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Observation).where(category.coding.where(code='laboratory').exists()).all(subject.exists())" should be true
      # Observation.subject.reference (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Observation).where(category.coding.where(code='laboratory').exists()).subject.all(reference.exists())" should be true
      # Observation.effective[x] (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Observation).where(category.coding.where(code='laboratory').exists()).all(effective.exists())" should be true
      # Observation.effective[x]:effectiveDateTime (SHOULD:able-to-populate)
      Then $ips at "Bundle.entry.resource.ofType(Observation).where(category.coding.where(code='laboratory').exists()).all(effective.ofType(dateTime).exists())" should be true
      # Observation.performer (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Observation).where(category.coding.where(code='laboratory').exists()).all(performer.exists())" should be true
      # Observation.value[x]:valueString (SHALL:populate-if-known) — the reference data carries it on some instances
      Then $ips at "Bundle.entry.resource.ofType(Observation).where(category.coding.where(code='laboratory').exists()).where(value.ofType(string).exists()).exists()" should be true
      # Observation.value[x]:valueQuantity (SHALL:populate-if-known) — the reference data carries it on some instances
      Then $ips at "Bundle.entry.resource.ofType(Observation).where(category.coding.where(code='laboratory').exists()).where(value.ofType(Quantity).exists()).exists()" should be true
      # The reference data does not exercise these; the Creator attests the capability.
      When Creator is asked for $canPopulate with "The reference patient has no data for these Observation elements. Can your system populate each of them when the information is known: [value[x]:valueCodeableConcept], [component]? Answer yes, or list the ones it cannot."
      Then $canPopulate should be "yes"

    @profile:Observation-results-radiology-uv-ips
    @covers:Observation.category:radiology @covers:Observation.code @covers:Observation.subject @covers:Observation.subject.reference
    @covers:Observation.effective[x] @covers:Observation.effective[x]:effectiveDateTime @covers:Observation.performer @covers:Observation.value[x]:valueString
    @covers:Observation.component
    Scenario: ips-creator-014 Observation Results - Radiology (IPS) — the Creator populates 8 elements when known
      # Instances: Bundle.entry.resource.ofType(Observation).where(category.coding.where(code='imaging').exists())
      # The reference data does not exercise these; the Creator attests the capability.
      When Creator is asked for $canPopulate with "The reference patient has no data for these Observation elements. Can your system populate each of them when the information is known: [category:radiology], [code], [subject], [subject.reference], [effective[x]], [effective[x]:effectiveDateTime], [performer], [value[x]:valueString], [component]? Answer yes, or list the ones it cannot."
      Then $canPopulate should be "yes"

    @profile:DiagnosticReport-uv-ips
    @covers:DiagnosticReport.code @covers:DiagnosticReport.subject @covers:DiagnosticReport.subject.reference @covers:DiagnosticReport.effective[x]
    @covers:DiagnosticReport.effective[x]:effectiveDateTime @covers:DiagnosticReport.performer @covers:DiagnosticReport.result:observation-results
    Scenario: ips-creator-015 DiagnosticReport (IPS) — the Creator populates 6 elements when known
      # Instances: Bundle.entry.resource.ofType(DiagnosticReport)
      # The reference data does not exercise these; the Creator attests the capability.
      When Creator is asked for $canPopulate with "The reference patient has no data for these DiagnosticReport elements. Can your system populate each of them when the information is known: [code], [subject], [subject.reference], [effective[x]], [effective[x]:effectiveDateTime], [performer], [result:observation-results]? Answer yes, or list the ones it cannot."
      Then $canPopulate should be "yes"

    @profile:Specimen-uv-ips
    @covers:Specimen.type @covers:Specimen.subject @covers:Specimen.subject.reference
    Scenario: ips-creator-016 Specimen (IPS) — the Creator populates 3 elements when known
      # Instances: Bundle.entry.resource.ofType(Specimen)
      # The reference data does not exercise these; the Creator attests the capability.
      When Creator is asked for $canPopulate with "The reference patient has no data for these Specimen elements. Can your system populate each of them when the information is known: [type], [subject], [subject.reference]? Answer yes, or list the ones it cannot."
      Then $canPopulate should be "yes"

    @profile:ImagingStudy-uv-ips
    @covers:ImagingStudy.identifier @covers:ImagingStudy.subject @covers:ImagingStudy.subject.reference @covers:ImagingStudy.started
    @covers:ImagingStudy.procedureCode @covers:ImagingStudy.reasonCode @covers:ImagingStudy.series @covers:ImagingStudy.series.uid
    @covers:ImagingStudy.series.modality @covers:ImagingStudy.series.instance @covers:ImagingStudy.series.instance.uid @covers:ImagingStudy.series.instance.sopClass
    Scenario: ips-creator-017 ImagingStudy (IPS) — the Creator populates 12 elements when known
      # Instances: Bundle.entry.resource.ofType(ImagingStudy)
      # The reference data does not exercise these; the Creator attests the capability.
      When Creator is asked for $canPopulate with "The reference patient has no data for these ImagingStudy elements. Can your system populate each of them when the information is known: [identifier], [subject], [subject.reference], [started], [procedureCode], [reasonCode], [series], [series.uid], [series.modality], [series.instance], [series.instance.uid], [series.instance.sopClass]? Answer yes, or list the ones it cannot."
      Then $canPopulate should be "yes"

    @profile:Procedure-uv-ips
    @covers:Procedure.code @covers:Procedure.subject @covers:Procedure.subject.reference @covers:Procedure.performed[x]
    @covers:Procedure.performed[x]:performedDateTime
    Scenario: ips-creator-018 Procedure (IPS) — the Creator populates 4 elements when known
      # Instances: Bundle.entry.resource.ofType(Procedure)
      # Procedure.code (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Procedure).all(code.exists())" should be true
      # Procedure.subject (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Procedure).all(subject.exists())" should be true
      # Procedure.subject.reference (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Procedure).subject.all(reference.exists())" should be true
      # Procedure.performed[x] (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Procedure).all(performed.exists())" should be true
      # Procedure.performed[x]:performedDateTime (SHOULD:able-to-populate)
      Then $ips at "Bundle.entry.resource.ofType(Procedure).all(performed.ofType(dateTime).exists())" should be true

    @profile:Device-observer-uv-ips
    @covers:Device.identifier @covers:Device.manufacturer @covers:Device.modelNumber
    Scenario: ips-creator-019 Device - Performer or Observer (IPS) — the Creator populates 3 elements when known
      # Instances: Bundle.entry.resource.ofType(Device)
      # The reference data does not exercise these; the Creator attests the capability.
      When Creator is asked for $canPopulate with "The reference patient has no data for these Device elements. Can your system populate each of them when the information is known: [identifier], [manufacturer], [modelNumber]? Answer yes, or list the ones it cannot."
      Then $canPopulate should be "yes"

    @profile:Device-uv-ips
    @covers:Device.type
    Scenario: ips-creator-020 Device (IPS) — the Creator populates 1 element when known
      # Instances: Bundle.entry.resource.ofType(Device)
      # Device.type (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Device).all(type.exists())" should be true

    @profile:DeviceUseStatement-uv-ips
    @covers:DeviceUseStatement.subject @covers:DeviceUseStatement.subject.reference @covers:DeviceUseStatement.timing[x] @covers:DeviceUseStatement.timing[x]:timingDateTime
    @covers:DeviceUseStatement.device
    Scenario: ips-creator-021 DeviceUseStatement (IPS) — the Creator populates 4 elements when known
      # Instances: Bundle.entry.resource.ofType(DeviceUseStatement)
      # DeviceUseStatement.subject (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(DeviceUseStatement).all(subject.exists())" should be true
      # DeviceUseStatement.subject.reference (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(DeviceUseStatement).subject.all(reference.exists())" should be true
      # DeviceUseStatement.device (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(DeviceUseStatement).all(device.exists())" should be true
      # The reference data does not exercise these; the Creator attests the capability.
      When Creator is asked for $canPopulate with "The reference patient has no data for these DeviceUseStatement elements. Can your system populate each of them when the information is known: [timing[x]], [timing[x]:timingDateTime]? Answer yes, or list the ones it cannot."
      Then $canPopulate should be "yes"

  Rule: The optional sections: alerts, pregnancy, social history

    @profile:Flag-alert-uv-ips
    @covers:Flag.extension:flag-priority @covers:Flag.category @covers:Flag.code @covers:Flag.subject
    @covers:Flag.subject.reference
    Scenario: ips-creator-022 Flag - Alert (IPS) — the Creator populates 5 elements when known
      # Instances: Bundle.entry.resource.ofType(Flag)
      # Flag.category (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Flag).all(category.exists())" should be true
      # Flag.code (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Flag).all(code.exists())" should be true
      # Flag.subject (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Flag).all(subject.exists())" should be true
      # Flag.subject.reference (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Flag).subject.all(reference.exists())" should be true
      # The reference data does not exercise these; the Creator attests the capability.
      When Creator is asked for $canPopulate with "The reference patient has no data for these Flag elements. Can your system populate each of them when the information is known: [extension:flag-priority]? Answer yes, or list the ones it cannot."
      Then $canPopulate should be "yes"

    @profile:Observation-pregnancy-edd-uv-ips
    @covers:Observation.code @covers:Observation.subject @covers:Observation.subject.reference @covers:Observation.effective[x]
    @covers:Observation.value[x]:valueDateTime
    Scenario: ips-creator-023 Observation Pregnancy - Expected Delivery Date (IPS) — the Creator populates 5 elements when known
      # Instances: Bundle.entry.resource.ofType(Observation).where(code.coding.where(code='11778-8' or code='11779-6' or code='11780-4').exists())
      # The reference data does not exercise these; the Creator attests the capability.
      When Creator is asked for $canPopulate with "The reference patient has no data for these Observation elements. Can your system populate each of them when the information is known: [code], [subject], [subject.reference], [effective[x]], [value[x]:valueDateTime]? Answer yes, or list the ones it cannot."
      Then $canPopulate should be "yes"

    @profile:Observation-pregnancy-outcome-uv-ips
    @covers:Observation.code @covers:Observation.subject @covers:Observation.subject.reference @covers:Observation.effective[x]
    @covers:Observation.value[x]:valueQuantity
    Scenario: ips-creator-024 Observation Pregnancy - Outcome (IPS) — the Creator populates 5 elements when known
      # Instances: Bundle.entry.resource.ofType(Observation).where(code.coding.where(code='11636-8' or code='11637-6' or code='11638-4' or code='11639-2' or code='11640-0' or code='11612-9' or code='11613-7' or code='11614-5' or code='33065-4').exists())
      # The reference data does not exercise these; the Creator attests the capability.
      When Creator is asked for $canPopulate with "The reference patient has no data for these Observation elements. Can your system populate each of them when the information is known: [code], [subject], [subject.reference], [effective[x]], [value[x]:valueQuantity]? Answer yes, or list the ones it cannot."
      Then $canPopulate should be "yes"

    @profile:Observation-pregnancy-status-uv-ips
    @covers:Observation.code @covers:Observation.subject @covers:Observation.subject.reference @covers:Observation.effective[x]
    @covers:Observation.value[x]:valueCodeableConcept @covers:Observation.hasMember @covers:Observation.hasMember.reference
    Scenario: ips-creator-025 Observation Pregnancy - Status (IPS) — the Creator populates 7 elements when known
      # Instances: Bundle.entry.resource.ofType(Observation).where(code.coding.where(code='82810-3').exists())
      # Observation.code (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Observation).where(code.coding.where(code='82810-3').exists()).all(code.exists())" should be true
      # Observation.subject (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Observation).where(code.coding.where(code='82810-3').exists()).all(subject.exists())" should be true
      # Observation.subject.reference (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Observation).where(code.coding.where(code='82810-3').exists()).subject.all(reference.exists())" should be true
      # Observation.effective[x] (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Observation).where(code.coding.where(code='82810-3').exists()).all(effective.exists())" should be true
      # Observation.value[x]:valueCodeableConcept (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Observation).where(code.coding.where(code='82810-3').exists()).all(value.ofType(CodeableConcept).exists())" should be true
      # The reference data does not exercise these; the Creator attests the capability.
      When Creator is asked for $canPopulate with "The reference patient has no data for these Observation elements. Can your system populate each of them when the information is known: [hasMember], [hasMember.reference]? Answer yes, or list the ones it cannot."
      Then $canPopulate should be "yes"

  Rule: Data types used throughout

    @profile:Observation-tobaccouse-uv-ips
    @covers:Observation.code @covers:Observation.subject @covers:Observation.subject.reference @covers:Observation.effective[x]
    Scenario: ips-creator-026 Observation Social History - Tobacco Use (IPS) — the Creator populates 4 elements when known
      # Instances: Bundle.entry.resource.ofType(Observation).where(code.coding.where(code='72166-2').exists())
      # Observation.code (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Observation).where(code.coding.where(code='72166-2').exists()).all(code.exists())" should be true
      # Observation.subject (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Observation).where(code.coding.where(code='72166-2').exists()).all(subject.exists())" should be true
      # Observation.subject.reference (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Observation).where(code.coding.where(code='72166-2').exists()).subject.all(reference.exists())" should be true
      # Observation.effective[x] (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Observation).where(code.coding.where(code='72166-2').exists()).all(effective.exists())" should be true

    @profile:Observation-alcoholuse-uv-ips
    @covers:Observation.code @covers:Observation.subject @covers:Observation.subject.reference @covers:Observation.effective[x]
    Scenario: ips-creator-027 Observation Social History - Alcohol Use (IPS) — the Creator populates 4 elements when known
      # Instances: Bundle.entry.resource.ofType(Observation).where(code.coding.where(code='74013-4').exists())
      # Observation.code (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Observation).where(code.coding.where(code='74013-4').exists()).all(code.exists())" should be true
      # Observation.subject (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Observation).where(code.coding.where(code='74013-4').exists()).all(subject.exists())" should be true
      # Observation.subject.reference (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Observation).where(code.coding.where(code='74013-4').exists()).subject.all(reference.exists())" should be true
      # Observation.effective[x] (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.ofType(Observation).where(code.coding.where(code='74013-4').exists()).all(effective.exists())" should be true

    @profile:CodeableConcept-uv-ips
    @covers:CodeableConcept.coding @covers:CodeableConcept.text
    Scenario: ips-creator-028 Codeable Concept (IPS) — the Creator populates 2 elements when known
      # CodeableConcept.coding (SHALL:populate-if-known) — the reference data carries it on some instances
      Then $ips at "Bundle.entry.resource.descendants().ofType(CodeableConcept).where(coding.exists()).exists()" should be true
      # CodeableConcept.text (SHALL:populate-if-known) — the reference data carries it on some instances
      Then $ips at "Bundle.entry.resource.descendants().ofType(CodeableConcept).where(text.exists()).exists()" should be true

    @profile:Coding-uv-ips
    @covers:Coding.system @covers:Coding.code
    Scenario: ips-creator-029 Coding with translations — the Creator populates 2 elements when known
      # Coding.system (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.descendants().ofType(Coding).all(system.exists())" should be true
      # Coding.code (SHALL:populate-if-known)
      Then $ips at "Bundle.entry.resource.descendants().ofType(Coding).all(code.exists())" should be true

  Rule: A patient with no known problems, allergies or medications still gets the required sections

    @profile:Composition-uv-ips
    @covers:Composition.section:sectionProblems.emptyReason @covers:Composition.section:sectionAllergies.emptyReason @covers:Composition.section:sectionMedications.emptyReason
    Scenario: ips-creator-900 Required sections carry an explicit no-information statement
      # The IG prefers a "no known …" entry over emptyReason; both are accepted here.
      Given Creator is informed "Now export the IPS of a patient for whom no problems, no allergies and no medications are known (as in https://hl7.org/fhir/uv/ips/Bundle-bundle-no-info-required-sections.json)."
      And Creator is asked for $ipsNoInfo with "Paste that IPS Bundle (JSON)"
      And $ipsNoInfo is a FHIR resource
      Then $ipsNoInfo should conform to "http://hl7.org/fhir/uv/ips/StructureDefinition/Bundle-uv-ips" ignoring slicing errors
      # Composition.section:sectionProblems.emptyReason (SHALL:populate-if-known) — or a "no known" entry
      And $ipsNoInfo at "Bundle.entry.resource.ofType(Composition).section.where(code.coding.where(code='11450-4').exists()).all(emptyReason.exists() or entry.exists())" should be true
      # Composition.section:sectionAllergies.emptyReason (SHALL:populate-if-known) — or a "no known" entry
      And $ipsNoInfo at "Bundle.entry.resource.ofType(Composition).section.where(code.coding.where(code='48765-2').exists()).all(emptyReason.exists() or entry.exists())" should be true
      # Composition.section:sectionMedications.emptyReason (SHALL:populate-if-known) — or a "no known" entry
      And $ipsNoInfo at "Bundle.entry.resource.ofType(Composition).section.where(code.coding.where(code='10160-0').exists()).all(emptyReason.exists() or entry.exists())" should be true
